gapi.loaded_0(function(_){var window=this;
try{
_.l=function(a){throw a;};_.n=void 0;_.q=!0;_.r=null;_.t=!1;_.aa=function(){return function(a){return a}};_.v=function(){return function(){}};_.ba=function(a){return function(c){this[a]=c}};_.x=function(a){return function(){return this[a]}};_.y=function(a){return function(){return a}};
_.ca=function(a){var c=typeof a;if("object"==c)if(a){if(a instanceof window.Array)return"array";if(a instanceof window.Object)return c;var f=window.Object.prototype.toString.call(a);if("[object Window]"==f)return"object";if("[object Array]"==f||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==f||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if("function"==c&&"undefined"==typeof a.call)return"object";return c};_.da=function(a){return a!==_.n};_.ea=function(a){return"array"==(0,_.ca)(a)};_.fa=function(a){var c=typeof a;return"object"==c&&a!=_.r||"function"==c};_.ga=function(a,c,f){return a.call.apply(a.bind,arguments)};
_.ha=function(a,c,f){a||(0,_.l)((0,window.Error)());if(2<arguments.length){var g=window.Array.prototype.slice.call(arguments,2);return function(){var f=window.Array.prototype.slice.call(arguments);window.Array.prototype.unshift.apply(f,g);return a.apply(c,f)}}return function(){return a.apply(c,arguments)}};_.D=function(a,c,f){_.D=window.Function.prototype.bind&&-1!=window.Function.prototype.bind.toString().indexOf("native code")?_.ga:_.ha;return _.D.apply(_.r,arguments)};
_.ia=function(a,c){var f=window.Array.prototype.slice.call(arguments,1);return function(){var c=window.Array.prototype.slice.call(arguments);c.unshift.apply(c,f);return a.apply(this,c)}};_.E=function(a,c){function f(){}f.prototype=c.prototype;a.p=c.prototype;a.prototype=new f;a.prototype.constructor=a};_._DumpException=function(a){(0,_.l)(a)};_.ja=_.ja||{};_.F=this;_.ka="closure_uid_"+window.Math.floor(2147483648*window.Math.random()).toString(36);_.la=window.Date.now||function(){return+new window.Date}; window.Function.prototype.bind=window.Function.prototype.bind||function(a,c){if(1<arguments.length){var f=window.Array.prototype.slice.call(arguments,1);f.unshift(this,a);return _.D.apply(_.r,f)}return(0,_.D)(this,a)};
_.ma=window.gapi||{};_.oa=window.___jsl=window.___jsl||{};_.pa=_.oa.df=_.oa.df||{};_.qa=window.gadgets||{};_.J=window.osapi=window.osapi||{};
}catch(e){_._DumpException(e)}
try{
window.___jsl=window.___jsl||{};
(window.___jsl.cd=window.___jsl.cd||[]).push({gwidget:{parsetags:"explicit"},appsapi:{plus_one_service:"/plus/v1"},client:{jsonpOverride:_.t},poshare:{hangoutContactPickerServer:"https://plus.google.com"},gappsutil:{required_scopes:["https://www.googleapis.com/auth/plus.me","https://www.googleapis.com/auth/plus.people.recommended"],display_on_page_ready:_.t},appsutil:{required_scopes:["https://www.googleapis.com/auth/plus.me","https://www.googleapis.com/auth/plus.people.recommended"],display_on_page_ready:_.t},
"oauth-flow":{authUrl:"https://accounts.google.com/o/oauth2/auth",proxyUrl:"https://accounts.google.com/o/oauth2/postmessageRelay",redirectUri:"postmessage"},iframes:{sharebox:{params:{json:"&"},url:":socialhost:/:session_prefix:_/sharebox/dialog"},plus:{url:":socialhost:/u/:session_index:/_/pages/badge"},":socialhost:":"https://plusone.google.com",card:{params:{s:"#",userid:"&"},url:":socialhost:/:session_prefix:_/hovercard/internalcard"},":signuphost:":"https://plus.google.com",plusone:{url:":socialhost:/:session_prefix:_/+1/fastbutton"},
plus_share:{url:":socialhost:/:session_prefix:_/+1/sharebutton?plusShare=true"}},poclient:{update_session:"google.updateSessionCallback"},"googleapis.config":{methods:{"chili.people.list":_.q,"pos.plusones.list":_.q,"pos.plusones.get":_.q,"chili.people.get":_.q,"pos.plusones.insert":_.q,"chili.activities.list":_.q,"pos.plusones.delete":_.q,"chili.activities.get":_.q,"chili.activities.search":_.q,"pos.plusones.getSignupState":_.q},requestCache:{enabled:_.q},versions:{chili:"v1",pos:"v1"},rpc:"/rpc", root:"https://www.googleapis.com","root-1p":"https://clients6.google.com",sessionCache:{enabled:_.q},transport:{isProxyShared:_.q},xd3:"/static/proxy.html",developerKey:"AIzaSyCKSbrvQasunBoV16zDH9R33D88CeLr9gQ",auth:{useInterimAuth:_.t}}});


}catch(e){_._DumpException(e)}
try{
_.ra=window.__GOOGLEAPIS;if(_.ra){_.ra.googleapis&&!_.ra["googleapis.config"]&&(_.ra["googleapis.config"]=_.ra.googleapis);_.sa=window.___jsl=window.___jsl||{};(_.sa.ci=_.sa.ci||[]).push(_.ra);window.__GOOGLEAPIS=_.n};

}catch(e){_._DumpException(e)}
try{
_.ta=function(a,c,f){a=a.split(".");f=f||_.F;!(a[0]in f)&&f.execScript&&f.execScript("var "+a[0]);for(var g;a.length&&(g=a.shift());)!a.length&&(0,_.da)(c)?f[g]=c:f=f[g]?f[g]:f[g]={}};_.ua=function(){return window.___jsl=window.___jsl||{}};_.va=function(a){var c=(0,_.ua)();c[a]=c[a]||[];return c[a]};_.wa=function(a){var c=(0,_.ua)();c.cfg=!a&&c.cfg||{};return c.cfg};_.xa=function(a){return"object"===typeof a&&/\[native code\]/.test(a.push)};
_.ya=function(a,c){if(c)for(var f in c)c.hasOwnProperty(f)&&(a[f]&&c[f]&&"object"===typeof a[f]&&"object"===typeof c[f]&&!(0,_.xa)(a[f])&&!(0,_.xa)(c[f])?(0,_.ya)(a[f],c[f]):c[f]&&"object"===typeof c[f]?(a[f]=(0,_.xa)(c[f])?[]:{},(0,_.ya)(a[f],c[f])):a[f]=c[f])};_.za=function(a){if(a){var c="",f=a.nodeType;if(3==f||4==f)c=a.nodeValue;else if(a.innerText)c=a.innerText;else if(a.innerHTML)c=a.innerHTML;else if(a.firstChild){c=[];for(a=a.firstChild;a;a=a.nextSibling)c.push((0,_.za)(a));c=c.join("")}return c}};
_.Aa=function(a){(0,_.wa)(_.q);var c=window.___gcfg,f=(0,_.va)("cu");if(c&&c!==window.___gu){var g={};(0,_.ya)(g,c);f.push(g);window.___gu=c}var c=(0,_.va)("cu"),h=window.document.scripts||window.document.getElementsByTagName("script")||[],g=[],k=[],m=(0,_.ua)().u;m&&k.push(m);(0,_.ua)().us&&k.push.apply(k,(0,_.ua)().us);for(m=0;m<h.length;++m)for(var p=h[m],s=0;s<k.length;++s)p.src&&0==p.src.indexOf(k[s])&&g.push(p);0==g.length&&h[h.length-1].src&&g.push(h[h.length-1]);for(h=0;h<g.length;++h)if(!g[h].getAttribute("gapi_processed")){g[h].setAttribute("gapi_processed",
_.q);if(k=(0,_.za)(g[h])){for(;0==k.charCodeAt(k.length-1);)k=k.substring(0,k.length-1);m=_.n;try{m=(new window.Function("return ("+k+"\n)"))()}catch(u){}if("object"===typeof m)k=m;else{try{m=(new window.Function("return ({"+k+"\n})"))()}catch(w){}k="object"===typeof m?m:{}}}else k=_.n;k&&c.push(k)}a&&(g={},(0,_.ya)(g,a),f.push(g));g=(0,_.va)("cd");a=0;for(c=g.length;a<c;++a)(0,_.ya)((0,_.wa)(),g[a]);g=(0,_.va)("ci");a=0;for(c=g.length;a<c;++a)(0,_.ya)((0,_.wa)(),g[a]);a=0;for(c=f.length;a<c;++a)(0,_.ya)((0,_.wa)(),
f[a])};_.L=function(a,c){if(!a)return(0,_.wa)();for(var f=a.split("/"),g=(0,_.wa)(),h=0,k=f.length;g&&"object"===typeof g&&h<k;++h)g=g[f[h]];return h===f.length&&g!==_.n?g:c};_.Ba=function(a,c){var f=a;if("string"===typeof a){for(var g=f={},h=a.split("/"),k=0,m=h.length;k<m-1;++k)var p={},g=g[h[k]]=p;g[h[k]]=c}(0,_.Aa)(f)};_.M=function(a,c){c="function"==typeof _.Ca&&(0,_.Ca)(a,c)||c;(0,_.ta)(a,c,_.n);var f=c;if(_.pa[a]){var g=_.pa[a];delete _.pa[a];g(f)}};
(0,_.Aa)();(0,_.M)("gapi.config.get",_.L);(0,_.M)("gapi.config.update",_.Ba);

}catch(e){_._DumpException(e)}
try{


}catch(e){_._DumpException(e)}
try{


}catch(e){_._DumpException(e)}
try{
_.nm=window.googleapis&&window.googleapis.server||{};

}catch(e){_._DumpException(e)}
try{
if(window.JSON&&window.JSON.parse&&window.JSON.stringify){_.La=function(a){return this[a]};_.Ma=/___$/;_.N={parse:function(a){try{return window.JSON.parse(a)}catch(c){return _.t}},stringify:function(a){function c(a){return f.call(this,a,_.La)}var f=window.JSON.stringify,g=window.Array.prototype.toJSON&&'"[{\\"x\\": 1}]"'===f([{x:1}])?c:f;try{return g(a,function(a,c){return!_.Ma.test(a)?c:_.n})}catch(h){return _.r}}}};
if(!window.JSON||!window.JSON.parse||!window.JSON.stringify)_.N=function(){function a(a){return 10>a?"0"+a:a}function c(a){var h,k,m;h=/[\"\\\x00-\x1f\x7f-\x9f]/g;switch(typeof a){case "string":return h.test(a)?'"'+a.replace(h,function(a){var c=f[a];if(c)return c;c=a.charCodeAt();return"\\u00"+window.Math.floor(c/16).toString(16)+(c%16).toString(16)})+'"':'"'+a+'"';case "number":return(0,window.isFinite)(a)?(0,window.String)(a):"null";case "boolean":case "null":return(0,window.String)(a);case "object":if(!a)return"null";
h=[];if("number"===typeof a.length&&!a.propertyIsEnumerable("length")){m=a.length;for(k=0;k<m;k+=1)h.push(c(a[k])||"null");return"["+h.join(",")+"]"}for(k in a)!/___$/.test(k)&&a.hasOwnProperty(k)&&"string"===typeof k&&(m=c(a[k]))&&h.push(c(k)+":"+m);return"{"+h.join(",")+"}"}return""}window.Date.prototype.toJSON=function(){return[this.getUTCFullYear(),"-",a(this.getUTCMonth()+1),"-",a(this.getUTCDate()),"T",a(this.getUTCHours()),":",a(this.getUTCMinutes()),":",a(this.getUTCSeconds()),"Z"].join("")};
var f={"\b":"\\b","\t":"\\t","\n":"\\n","\f":"\\f","\r":"\\r",'"':'\\"',"\\":"\\\\"};return{stringify:c,parse:function(a){return/^[\],:{}\s]*$/.test(a.replace(/\\["\\\/b-u]/g,"@").replace(/"[^"\\\n\r]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g,"]").replace(/(?:^|:|,)(?:\s*\[)+/g,""))?eval("("+a+")"):_.t}}}();
_.N.zi=function(a){var c={};if(a===_.r||a===_.n)return c;for(var f in a)if(a.hasOwnProperty(f)){var g=a[f];_.r===g||_.n===g||(c[f]="string"===typeof g?g:_.N.stringify(g))}return c};(0,_.M)("gadgets.json.flatten",_.N.zi);(0,_.M)("gadgets.json.parse",_.N.parse);(0,_.M)("gadgets.json.stringify",_.N.stringify);(0,_.M)("gadgets.json.flatten",_.N.zi);(0,_.M)("gadgets.json.parse",_.N.parse);(0,_.M)("gadgets.json.stringify",_.N.stringify);


}catch(e){_._DumpException(e)}
try{


}catch(e){_._DumpException(e)}
try{
_.O=_.O||{};

}catch(e){_._DumpException(e)}
try{
_.Ra=function(a,c){return window.String.fromCharCode(c)};_.O=_.O||{};_.Sa={"0":_.t,10:_.q,13:_.q,34:_.q,39:_.q,60:_.q,62:_.q,92:_.q,8232:_.q,8233:_.q,65282:_.q,65287:_.q,65308:_.q,65310:_.q,65340:_.q};_.O.escape=function(a,c){if(a){if("string"===typeof a)return _.O.Yd(a);if("array"===typeof a)for(var f=0,g=a.length;f<g;++f)a[f]=_.O.escape(a[f]);else if("object"===typeof a&&c){f={};for(g in a)a.hasOwnProperty(g)&&(f[_.O.Yd(g)]=_.O.escape(a[g],_.q));return f}}return a}; _.O.Yd=function(a){if(!a)return a;for(var c=[],f,g,h=0,k=a.length;h<k;++h)f=a.charCodeAt(h),g=_.Sa[f],g===_.q?c.push("&#",f,";"):g!==_.t&&c.push(a.charAt(h));return c.join("")};_.O.Fq=function(a){return!a?a:a.replace(/&#([0-9]+);/g,_.Ra)};


}catch(e){_._DumpException(e)}
try{
_.Nl=function(a){var c="";if(3==a.nodeType||4==a.nodeType)c=a.nodeValue;else if(a.innerText)c=a.innerText;else if(a.innerHTML)c=a.innerHTML;else if(a.firstChild){c=[];for(a=a.firstChild;a;a=a.nextSibling)c.push((0,_.Nl)(a));c=c.join("")}return c};_.O=_.O||{};_.O.createElement=function(a){var c;if(!window.document.body||window.document.body.namespaceURI)try{c=window.document.createElementNS("http://www.w3.org/1999/xhtml",a)}catch(f){}return c||window.document.createElement(a)};
_.O.cg=function(a){var c=_.O.createElement("iframe");try{var f=["<","iframe"],g=a||{},h;for(h in g)g.hasOwnProperty(h)&&(f.push(" "),f.push(h),f.push('="'),f.push(_.O.Yd(g[h])),f.push('"'));f.push("></");f.push("iframe");f.push(">");var k=_.O.createElement(f.join(""));if(k&&(!c||k.tagName==c.tagName&&k.namespaceURI==c.namespaceURI))c=k}catch(m){}var f=c,a=a||{},p;for(p in a)a.hasOwnProperty(p)&&(f[p]=a[p]);return c};
_.O.Ci=function(){if(window.document.body)return window.document.body;try{var a=window.document.getElementsByTagNameNS("http://www.w3.org/1999/xhtml","body");if(a&&1==a.length)return a[0]}catch(c){}return window.document.documentElement||window.document};_.O.gq=function(a){return(0,_.Nl)(a)};


}catch(e){_._DumpException(e)}
try{
_.O=_.O||{};_.hb=[];_.O.sq=function(a){_.hb.push(a)};_.O.yq=function(){for(var a=0,c=_.hb.length;a<c;++a)_.hb[a]()};

}catch(e){_._DumpException(e)}
try{
_.jb=window.gadgets&&window.gadgets.config&&window.gadgets.config.get;_.jb&&(0,_.Ba)((0,_.jb)());_.ib={N:function(a,c,f){f&&f((0,_.L)())},get:function(a){return(0,_.L)(a)},update:function(a,c){c&&(0,_.l)("Config replacement is not supported");(0,_.Ba)(a)},S:(0,_.v)()};
(0,_.M)("gadgets.config.register",_.ib.N);(0,_.M)("gadgets.config.get",_.ib.get);(0,_.M)("gadgets.config.init",_.ib.S);(0,_.M)("gadgets.config.update",_.ib.update);

}catch(e){_._DumpException(e)}
try{
_.O=_.O||{};_.Ta=_.r;
_.O.U=function(a){var c="undefined"===typeof a;if(_.Ta!==_.r&&c)return _.Ta;for(var f={},a=a||window.document.location.href,g=a.indexOf("?"),h=a.indexOf("#"),a=(-1===h?a.substr(g+1):[a.substr(g+1,h-g-1),"&",a.substr(h+1)].join("")).split("&"),g=window.decodeURIComponent?window.decodeURIComponent:window.unescape,h=0,k=a.length;h<k;++h){var m=a[h].indexOf("=");if(-1!==m){var p=a[h].substring(0,m),m=a[h].substring(m+1),m=m.replace(/\+/g," ");try{f[p]=g(m)}catch(s){}}}c&&(_.Ta=f);return f};_.O.U();
(0,_.M)("gadgets.util.getUrlParameters",_.O.U);

}catch(e){_._DumpException(e)}
try{
_.kb=window.gapi&&window.gapi.util||{};

}catch(e){_._DumpException(e)}
try{
_.kb.ma=function(a){if(!a)return"";a=a.split("#")[0].split("?")[0];a=a.toLowerCase();0==a.indexOf("//")&&(a=window.location.protocol+a);/^\w*:\/\//.test(a)||(a=window.location.href);var c=a.substring(a.indexOf("://")+3),f=c.indexOf("/");-1!=f&&(c=c.substring(0,f));var a=a.substring(0,a.indexOf("://")),f="",g=c.indexOf(":");if(-1!=g){var h=c.substring(g+1),c=c.substring(0,g);if("http"===a&&"80"!==h||"https"===a&&"443"!==h)f=":"+h}return a+"://"+c+f};


}catch(e){_._DumpException(e)}
try{
if(window.gapi&&window.gapi.rpc){_.mb=window.gapi.rpc;_.mb.call=_.mb.call;_.mb.N=_.mb.register;_.mb.Vb=_.mb.unregister;_.mb.wc=_.mb.setup;_.mb.ap=_.mb.sw;_.lb=_.mb}else{_.ob=function(a){if(a.f in{})return _.t;var c=a.t,f=_.nb[a.r],a=a.origin;return f&&(f.Ld===c||!f.Ld&&!c)&&(a===f.origin||"*"===f.origin)};_.ub=function(a,c,f){a=(0,_.pb)(a);_.qb[a.name]={ym:c,qe:a.qe,jp:f||_.ob};(0,_.tb)()};_.xb=function(a){var c=a.c;if(!c)return(0,_.v)();var f=a.r,g=a.g?"legacy__":"";return function(){var a=[].slice.call(arguments,
0);_.vb?a.unshift(f,g+"__cb",_.r,c):a.unshift(f,g+"__cb"+c,_.r);_.wb.apply(_.r,a)}};_.Eb=function(a,c,f,g){var h=_.yb,k=_.zb,m=_.nb[c],p=h,s=(0,_.Ab)(c);if(m&&".."!==c){if(s.ah){if(!(k=_.nb[c].Eo)){k=_.r;k=_.Bb?_.Bb.substring(1).split("/"):[_.yb];p=k.length-1;for(c=window.parent;c!==window.top;){var u=c.parent;if(!p--){for(var w=_.r,A=u.frames.length,B=0;B<A;++B)u.frames[B]==c&&(w=B);k.unshift("{"+w+"}")}c=u}k="/"+k.join("/")}p=k}else p=h="..";k=m.Ld}m=p;if(g&&s){p=_.ob;if(s.ah)var p=s.id.split("/"),
H=p[p.length-1],I=s.origin,p=function(a){var c=a.origin;return a.f==H&&(I==c||"*"==I)};_.vb?_.Cb["_"+ ++_.Db]=[g,p]:(0,_.ub)("__cb"+(0,window.String)(++_.Db),g,p);g=_.Db}else g=_.r;f={s:a,f:h,r:m,t:k,c:g,a:f};a=(0,_.pb)(a);f.s=a.name;f.g=a.qe;return f};_.Hb=function(a){var c=_.nb[a];if(c&&c.yb){var f=c.Ah;c.Ah=[];if(_.Fb)f.length&&(f=(0,_.Eb)("_processBatch",a,[f]),_.Gb.send(a,_.N.stringify(f),c.origin));else for(;f.length;)_.Gb.send(a,_.N.stringify(f.shift()),c.origin)}};_.pb=function(a){return 0===
a.indexOf("legacy__")?{name:a.substring(8),qe:_.q}:{name:a,qe:_.t}};_.tb=function(){for(var a=0,c;c=_.Ib[a];++a){var f=c.Jd,g=f.s,h=_.qb[g]||_.qb["*"];if(h&&(_.Ib.splice(a,1),--a,f.origin=c.origin,c=(0,_.xb)(f),f.callback=c,h.jp(f))){if("__cb"!==g&&!!h.qe!=!!f.g)break;f=h.ym.apply(f,f.a);f!==_.n&&c(f)}}};_.Ab=function(a){var c=_.t,a=a.split("|"),f=a[0];0<=f.indexOf("/")&&(c=_.q);return{id:f,origin:a[1]||"*",ah:c}};_.Lb=function(a,c){var f=(0,_.Ab)(a),a=f.id;if(!_.nb.hasOwnProperty(a)){var g=_.zb,
h=_.r;f.ah?(g=_.r,h=f.origin):".."!==a?(g=window.document.getElementById(a).src,h=_.kb.ma(g),g=(0,_.Jb)(g).rpctoken):h=_.kb.ma(_.Kb);f.origin&&(h=f.origin);_.nb[a]={Ld:g,Ah:[],origin:h,Eo:c,Xj:function(){var c=a;_.nb[c].yb=1;(0,_.Hb)(c)}};_.Gb.wc(a,_.nb[a].Xj)}return _.nb[a].Xj};_.Mb=function(){return"function"===typeof window.postMessage||"object"===typeof window.postMessage};_.wb=function(a,c,f,g){a=a||"..";(0,_.Lb)(a);var a=a.split("|",1)[0],h=[].slice.call(arguments,3),h=(0,_.Eb)(c,a,h,f);_.nb[a].Ah.push(h);
var k=a;_.Nb[k]||(_.Nb[k]=window.setTimeout(function(){_.Nb[k]=_.t;(0,_.Hb)(k)},0))};_.Ob={call:_.wb,N:_.ub,Vb:function(a){delete _.qb[(0,_.pb)(a).name]},wc:_.Lb,ap:_.Mb};if((0,_.Mb)()){_.Fb=_.t;_.Db=0;_.Ib=[];_.nb={};_.qb={};_.Jb=_.O.U;_.Pb=(0,_.Jb)();_.zb=_.Pb.rpctoken;_.Kb=_.Pb.parent||window.document.referrer;_.yb=window!==window.top&&window.name||"..";_.Bb=_.r;_.Nb={};_.Qb={rm:function(a,c){var f=_.N.parse(a);_.Ib.push({Jd:f,origin:c});(0,_.tb)()},$m:function(a){var c=window;"/"==a.charAt(0)&&
(a=a.substring(1),c=window.top);for(a=a.split("/");a.length;){var f;f=a.shift();"{"==f.charAt(0)&&"}"==f.charAt(f.length-1)&&(f=f.substring(1,f.length-1));if(".."===f)c=c.parent;else if(".."!==f&&c.frames[f])c=c.frames[f],"postMessage"in c||(0,_.l)("Not a window");else return _.r}return c},b:_.yb,Dg:function(a){return(a=_.nb[a])&&a.Ld},d:function(a){_.Bb=a}};_.Rb=function(a){a=_.N.parse(a);return a!=_.r&&"object"===typeof a&&!!a.g};_.Tb=function(a){var c=(0,window.String)(a.data),f=0!==c.indexOf("!_");
f||(c=c.substring(2));var g=(0,_.Rb)(c);if(f==g){if(!g&&(f=_.r,0==c.indexOf("{h:'")&&c.indexOf("'}")==c.length-2&&(f=(0,window.unescape)(c.substring(4,c.length-2))),f)){if(_.Sb[f])_.Sb[f]();return}var h=a.origin;window.setTimeout(function(){_.Qb.rm(c,h)},0)}};_.Sb={};_.Ub=_.r;(_.Ub=window.addEventListener)?(0,_.Ub)("message",_.Tb,_.t):(_.Ub=window.attachEvent)&&(0,_.Ub)("onmessage",_.Tb);window.___jsl=window.___jsl||{};_.Vb=window.___jsl;_.Vb.RPMQ=_.Vb.RPMQ||[];_.Vb.RPMQ.push(_.Tb);if(window!==window.parent){_.Wb=
window.parent;_.Xb="{h:'"+(0,window.escape)(window.name)+"'}";_.Zb=(0,_.Rb)(_.Xb)?"":"!_";_.Wb.postMessage(_.Zb+_.Xb,"*")}_.Gb={wc:function(a,c){".."==a?c():_.Sb[a]=c},send:function(a,c,f){var a=_.Qb.$m(a),g=(0,_.Rb)(c)?"":"!_";a.postMessage(g+c,f)}};_.Cb={};_.vb=_.q;(0,_.ub)("__cb",function(a,c){var f=_.Cb["_"+a];f&&f[1](this)&&f[0].call(this,c)},(0,_.y)(_.q));(0,_.ub)("_processBatch",function(a){for(;a.length;){var c=a.shift();_.Ib.push({Jd:c,origin:this.origin})}(0,_.tb)()},(0,_.y)(_.q));(0,_.Lb)("..")}_.lb= _.Ob}_.$b=_.lb;


}catch(e){_._DumpException(e)}
try{


}catch(e){_._DumpException(e)}
try{
_.cc=_.cc||{};_.cc.hk=_.r;_.cc.Cj=_.r;_.cc.af=_.r;_.cc.frameElement=_.r;_.cc=_.cc||{};
if(!_.cc.Qh){_.fc=function(a){var c=_.N.parse(a.data);if(c&&c.f){var f=_.P.Nb(c.f);(!_.dc||!("undefined"!==typeof a.origin?a.origin!==f:a.domain!==/^.+:\/\/([^:]+).*/.exec(f)[1]))&&(0,_.ec)(c,a.origin)}};_.dc=_.q;_.cc.Qh={Di:(0,_.y)("wpm"),b:(0,_.y)(_.q),S:function(a,c){_.ib.N("rpc",_.r,function(a){if("true"===(0,window.String)((a&&a.rpc||{}).disableForceSecure))_.dc=_.t});_.ec=a;_.gc=c;"undefined"!=typeof window.addEventListener?window.addEventListener("message",_.fc,_.t):"undefined"!=typeof window.attachEvent&&
window.attachEvent("onmessage",_.fc);window.___jsl=window.___jsl||{};var f=window.___jsl;f.RPMQ=f.RPMQ||[];f.RPMQ.push(_.fc);(0,_.gc)("..",_.q);return _.q},wc:function(a){(0,_.gc)(a,_.q);return _.q},call:function(a,c,f){var g=_.P.Nb(a),h=_.P.bi(a);g?window.setTimeout(function(){h.postMessage(_.N.stringify(f),g)},0):".."!=a&&(0,_.Ia)("No relay set (used as window.postMessage targetOrigin), cannot send cross-domain message");return _.q}}};
_.cc=_.cc||{};
if(!_.cc.Pe){_.hc=_.cc;_.kc=function(a,c){function f(){a.apply({},arguments)}_.ic[c]=_.ic[c]||f;return _.jc+"."+c};_.rc=function(){if(_.lc===_.r&&window.document.body&&_.mc){var a=_.mc+"?cb="+window.Math.random()+"&origin="+_.nc+"&jsl=1",c=window.document.createElement("div");c.style.height="1px";c.style.width="1px";a='<object height="1" width="1" id="'+_.oc+'" type="application/x-shockwave-flash"><param name="allowScriptAccess" value="always"></param><param name="movie" value="'+a+'"></param><embed type="application/x-shockwave-flash" allowScriptAccess="always" src="'+
a+'" height="1" width="1"></embed></object>';window.document.body.appendChild(c);c.innerHTML=a;_.lc=c.firstChild}++_.pc;_.qc!==_.r&&(_.lc!==_.r||50<=_.pc)?window.clearTimeout(_.qc):_.qc=window.setTimeout(_.rc,100)};_.zc=function(){_.sc[".."]||((0,_.tc)(".."),_.xc++,50<=_.xc&&_.yc!==_.r?(window.clearTimeout(_.yc),_.yc=_.r):_.yc=window.setTimeout(_.zc,100))};_.Bc=function(){if(_.lc!==_.r&&_.lc.setup)for(;0<_.Ac.length;){var a=_.Ac.shift(),c=a.dp;_.lc.setup(a.Ld,".."===c?_.P.Lf:c,".."===c?"INNER":"OUTER")}_.qc!==
_.r&&window.clearTimeout(_.qc);_.qc=_.r};_.Cc=function(){!_.sc[".."]&&_.yc===_.r&&(_.yc=window.setTimeout(_.zc,100))};_.Dc=function(a,c,f){var c=_.P.Nb(a),g=_.P.Lb(a);_.lc["sendMessage_"+(".."===a?_.P.Lf:a)+"_"+g+"_"+(".."===a?"INNER":"OUTER")].call(_.lc,_.N.stringify(f),c);return _.q};_.Gc=function(a,c){var f=_.N.parse(a),g=f._scr;g?((0,_.Ec)(g,_.q),_.sc[g]=_.q,".."!==g&&(0,_.tc)(g,_.q)):window.setTimeout(function(){(0,_.Fc)(f,c)},0)};_.tc=function(a,c){var f=_.P.Lf,g={};g._scr=c?"..":f;g._pnt=f;
(0,_.Dc)(a,f,g)};_.oc="___xpcswf";_.mc=_.r;_.Hc=_.t;_.Fc=_.r;_.Ec=_.r;_.lc=_.r;_.Ac=[];_.qc=_.r;_.pc=0;_.xc=0;_.yc=_.r;_.sc={};_.nc=window.location.protocol+"//"+window.location.host;window.___jsl=window.___jsl||{};_.Ic=window.___jsl._fm={};_.jc="___jsl._fm";_.ic=_.Ic;_.ib.N("rpc",_.r,function(a){_.Hc&&(_.mc=a&&a.rpc&&a.rpc.commSwf||"//xpc.googleusercontent.com/gadgets/xpc.swf")});(0,_.kc)(_.Bc,"ready");(0,_.kc)(_.Cc,"setupDone");(0,_.kc)(_.Gc,"receiveMessage");_.hc.Pe={Di:(0,_.y)("flash"),b:(0,_.y)(_.q), S:function(a,c){_.Fc=a;_.Ec=c;return _.Hc=_.q},wc:function(a,c){_.Ac.push({Ld:c,dp:a});_.lc===_.r&&_.qc===_.r&&(_.qc=window.setTimeout(_.rc,100));return _.q},call:_.Dc,Ul:_.Gc,d:_.Bc,i:_.Cc}};
if(!window.gadgets||!window.gadgets.rpc){_.Oc=function(a,c){if(!_.Jc[a]){var f=_.Kc;c||(f=_.Lc);_.Jc[a]=f;for(var g=_.Mc[a]||[],h=0;h<g.length;++h){var k=g[h];k.t=_.Nc[a];f.call(a,k.f,k)}_.Mc[a]=[]}};_.Tc=function(a,c,f,g,h){function k(){_.Pc=_.q}if(!_.Nc[c]||_.Nc[c]!==f)(0,_.Ia)("Invalid auth token. "+_.Nc[c]+" vs "+f),(0,_.Qc)(c,2);h.onunload=function(){_.Rc[c]&&!_.Pc&&((0,_.Qc)(c,1),_.P.Gd(c))};_.Sc||("undefined"!=typeof window.addEventListener?window.addEventListener("unload",k,_.t):"undefined"!=
typeof window.attachEvent&&window.attachEvent("onunload",k),_.Sc=_.q);g=_.N.parse((0,window.decodeURIComponent)(g))};_.Wc=function(a,c){if(a&&"string"===typeof a.s&&"string"===typeof a.f&&a.a instanceof window.Array)if(_.Nc[a.f]&&_.Nc[a.f]!==a.t&&((0,_.Ia)("Invalid auth token. "+_.Nc[a.f]+" vs "+a.t),(0,_.Qc)(a.f,2)),"__ack"===a.s)window.setTimeout(function(){(0,_.Oc)(a.f,_.q)},0);else{a.c&&(a.callback=function(c){_.P.call(a.f,(a.g?"legacy__":"")+"__cb",_.r,a.c,c)});if(c){var f=(0,_.Uc)(c);a.origin=
c;var g=a.r;if(!g||(0,_.Uc)(g)!=f)g=c;a.referer=g}f=(_.Vc[a.s]||_.Vc[""]).apply(a,a.a);a.c&&"undefined"!==typeof f&&_.P.call(a.f,"__cb",_.r,a.c,f)}};_.Uc=function(a){if(!a)return"";a=a.split("#")[0].split("?")[0];a=a.toLowerCase();0==a.indexOf("//")&&(a=window.location.protocol+a);-1==a.indexOf("://")&&(a=window.location.protocol+"//"+a);var c=a.substring(a.indexOf("://")+3),f=c.indexOf("/");-1!=f&&(c=c.substring(0,f));var a=a.substring(0,a.indexOf("://")),f="",g=c.indexOf(":");if(-1!=g){var h=c.substring(g+
1),c=c.substring(0,g);if("http"===a&&"80"!==h||"https"===a&&"443"!==h)f=":"+h}return a+"://"+c+f};_.Xc=function(a){if("/"==a.charAt(0)){var c=a.indexOf("|");return{id:0<c?a.substring(1,c):a.substring(1),origin:0<c?a.substring(c+1):_.r}}return _.r};_.Yc=function(a){if("undefined"===typeof a||".."===a)return window.parent;var c=(0,_.Xc)(a);if(c)return window.top.frames[c.id];a=(0,window.String)(a);return(c=window.frames[a])?c:(c=window.document.getElementById(a))&&c.contentWindow?c.contentWindow:_.r};
_.Zc=function(a,c){if(_.Rc[a]!==_.q){"undefined"===typeof _.Rc[a]&&(_.Rc[a]=0);var f=(0,_.Yc)(a);(".."===a||f!=_.r)&&_.Kc.wc(a,c)===_.q?_.Rc[a]=_.q:_.Rc[a]!==_.q&&10>_.Rc[a]++?window.setTimeout(function(){(0,_.Zc)(a,c)},500):(_.Jc[a]=_.Lc,_.Rc[a]=_.q)}};_.ad=function(a){(a=_.$c[a])&&"/"===a.substring(0,1)&&(a="/"===a.substring(1,2)?window.document.location.protocol+a:window.document.location.protocol+"//"+window.document.location.host+a);return a};_.cd=function(a,c,f){c&&!/http(s)?:\/\/.+/.test(c)&&
(0==c.indexOf("//")?c=window.location.protocol+c:"/"==c.charAt(0)?c=window.location.protocol+"//"+window.location.host+c:-1==c.indexOf("://")&&(c=window.location.protocol+"//"+c));_.$c[a]=c;"undefined"!==typeof f&&(_.bd[a]=!!f)};_.dd=function(a,c){c=c||"";_.Nc[a]=(0,window.String)(c);(0,_.Zc)(a,c)};_.gd=function(a){a=(a.passReferrer||"").split(":",2);_.ed=a[0]||"none";_.fd=a[1]||"origin"};_.hd=function(a){"true"===(0,window.String)(a.useLegacyProtocol)&&(_.Kc=_.cc.af||_.Lc,_.Kc.S(_.Wc,_.Oc))};_.jd=
function(a,c,f){if(".."===a){var g=f||_.id.rpctoken||_.id.ifpctok||"",a=function(a){a=a&&a.rpc||{};(0,_.gd)(a);var f=a.parentRelayUrl||"",f=(0,_.Uc)(_.id.parent||c)+f;(0,_.cd)("..",f,"true"===(0,window.String)(a.useLegacyProtocol));(0,_.hd)(a);(0,_.dd)("..",g)};!_.id.parent&&c?a({}):_.ib.N("rpc",_.r,a)}else a:{var h=_.r;if("/"!=a.charAt(0)){if(!_.O)break a;(h=window.document.getElementById(a))||(0,_.l)((0,window.Error)("g`"+a))}var h=h&&h.src,k=c||_.P.ma(h);(0,_.cd)(a,k);h=_.O.U(h);(0,_.dd)(a,f||
h.rpctoken)}};_.Vc={};_.$c={};_.bd={};_.Nc={};_.kd=0;_.ld={};_.Rc={};_.id={};_.Jc={};_.Mc={};_.ed=_.r;_.fd=_.r;_.md=window.top!==window.self;_.nd=window.name;_.Qc=(0,_.v)();_.od=window.console;_.pd=_.od&&_.od.log&&function(a){_.od.log(a)}||(0,_.v)();_.qd=function(a){return function(){(0,_.pd)(a+": call ignored")}};_.Lc={getCode:(0,_.y)("noop"),isParentVerifiable:(0,_.y)(_.q),init:(0,_.qd)("init"),setup:(0,_.qd)("setup"),call:(0,_.qd)("call")};_.O&&(_.id=_.O.U());_.Pc=_.t;_.Sc=_.t;_.Kc=function(){if("flash"==
_.id.rpctx)return _.cc.Pe;if("rmr"==_.id.rpctx)return _.cc.hk;var a="function"===typeof window.postMessage?_.cc.Qh:"object"===typeof window.postMessage?_.cc.Qh:window.ActiveXObject?_.cc.Pe?_.cc.Pe:_.cc.Cj?_.cc.Cj:_.cc.af:0<window.navigator.userAgent.indexOf("WebKit")?_.cc.hk:"Gecko"===window.navigator.product?_.cc.frameElement:_.cc.af;a||(a=_.Lc);return a}();_.Vc[""]=function(){(0,_.pd)("Unknown RPC service: "+this.s)};_.Vc.__cb=function(a,c){var f=_.ld[a];f&&(delete _.ld[a],f.call(this,c))};_.P=
{fa:function(a){"function"===typeof a.Io&&(_.Qc=a.Io)},N:function(a,c){("__cb"===a||"__ack"===a)&&(0,_.l)((0,window.Error)("h"));""===a&&(0,_.l)((0,window.Error)("i"));_.Vc[a]=c},Vb:function(a){("__cb"===a||"__ack"===a)&&(0,_.l)((0,window.Error)("j"));""===a&&(0,_.l)((0,window.Error)("k"));delete _.Vc[a]},we:function(a){_.Vc[""]=a},Ee:function(){delete _.Vc[""]},Zd:(0,_.v)(),call:function(a,c,f,g){var a=a||"..",h="..";".."===a?h=_.nd:"/"==a.charAt(0)&&(h=_.P.ma(window.location.href),h="/"+_.nd+(h?
"|"+h:""));++_.kd;f&&(_.ld[_.kd]=f);var k={s:c,f:h,c:f?_.kd:0,a:window.Array.prototype.slice.call(arguments,3),t:_.Nc[a],l:!!_.bd[a]},m;a:if("bidir"===_.ed||"c2p"===_.ed&&".."===a||"p2c"===_.ed&&".."!==a){m=window.location.href;var p="?";if("query"===_.fd)p="#";else if("hash"===_.fd)break a;p=m.lastIndexOf(p);p=-1===p?m.length:p;m=m.substring(0,p)}else m=_.r;m&&(k.r=m);".."!==a&&(0,_.Xc)(a)==_.r&&!window.document.getElementById(a)||(m=_.Jc[a],!m&&(0,_.Xc)(a)!==_.r&&(m=_.Kc),0===c.indexOf("legacy__")&&
(m=_.Kc,k.s=c.substring(8),k.c=k.c?k.c:_.kd),k.g=_.q,k.r=h,m?(_.bd[a]&&(m=_.cc.af),m.call(a,h,k)===_.t&&(_.Jc[a]=_.Lc,_.Kc.call(a,h,k))):_.Mc[a]?_.Mc[a].push(k):_.Mc[a]=[k])},de:_.ad,Wc:_.cd,Vc:_.dd,xc:_.jd,Lb:function(a){return _.Nc[a]},Gd:function(a){delete _.$c[a];delete _.bd[a];delete _.Nc[a];delete _.Rc[a];delete _.Jc[a]},ce:function(){return _.Kc.Di()},ue:function(a,c){4<a.length?_.Kc.Ul(a,_.Wc):_.Tc.apply(_.r,a.concat(c))},ve:function(a){a.a=window.Array.prototype.slice.call(a.a);window.setTimeout(function(){(0,_.Wc)(a)},
0)},ma:_.Uc,Nb:function(a){var c=_.r,c=(0,_.ad)(a);c||(c=(c=(0,_.Xc)(a))?c.origin:".."==a?_.id.parent:window.document.getElementById(a).src);return(0,_.Uc)(c)},S:function(){_.Kc.S(_.Wc,_.Oc)===_.t&&(_.Kc=_.Lc);_.md?(0,_.jd)(".."):_.ib.N("rpc",_.r,function(a){a=a.rpc||{};(0,_.gd)(a);(0,_.hd)(a)})},bi:_.Yc,Tl:_.Xc,b:"__ack",Lf:_.nd||"..",j:0,i:1,d:2};_.P.S()}else if("undefined"==typeof _.P||!_.P)_.P=window.gadgets.rpc,_.P.fa=_.P.config,_.P.N=_.P.register,_.P.Vb=_.P.unregister,_.P.we=_.P.registerDefault,
_.P.Ee=_.P.unregisterDefault,_.P.Zd=_.P.forceParentVerifiable,_.P.call=_.P.call,_.P.de=_.P.getRelayUrl,_.P.Wc=_.P.setRelayUrl,_.P.Vc=_.P.setAuthToken,_.P.xc=_.P.setupReceiver,_.P.Lb=_.P.getAuthToken,_.P.Gd=_.P.removeReceiver,_.P.ce=_.P.getRelayChannel,_.P.ue=_.P.receive,_.P.ve=_.P.receiveSameDomain,_.P.ma=_.P.getOrigin,_.P.Nb=_.P.getTargetOrigin,_.P.bi=_.P._getTargetWin,_.P.Tl=_.P._parseSiblingId;
(0,_.M)("gadgets.rpc.config",_.P.fa);(0,_.M)("gadgets.rpc.register",_.P.N);(0,_.M)("gadgets.rpc.unregister",_.P.Vb);(0,_.M)("gadgets.rpc.registerDefault",_.P.we);(0,_.M)("gadgets.rpc.unregisterDefault",_.P.Ee);(0,_.M)("gadgets.rpc.forceParentVerifiable",_.P.Zd);(0,_.M)("gadgets.rpc.call",_.P.call);(0,_.M)("gadgets.rpc.getRelayUrl",_.P.de);(0,_.M)("gadgets.rpc.setRelayUrl",_.P.Wc);(0,_.M)("gadgets.rpc.setAuthToken",_.P.Vc);(0,_.M)("gadgets.rpc.setupReceiver",_.P.xc);
(0,_.M)("gadgets.rpc.getAuthToken",_.P.Lb);(0,_.M)("gadgets.rpc.removeReceiver",_.P.Gd);(0,_.M)("gadgets.rpc.getRelayChannel",_.P.ce);(0,_.M)("gadgets.rpc.receive",_.P.ue);(0,_.M)("gadgets.rpc.receiveSameDomain",_.P.ve);(0,_.M)("gadgets.rpc.getOrigin",_.P.ma);(0,_.M)("gadgets.rpc.getTargetOrigin",_.P.Nb);


}catch(e){_._DumpException(e)}
try{


}catch(e){_._DumpException(e)}
try{
_.rd=_.kb=_.kb||{};_.sd={Sh:"bsh",Vh:"h"};window.___jsl=window.___jsl||{};_.rd.Ud={Bm:function(){return window.___jsl[_.sd.Sh]},yg:function(){return window.___jsl[_.sd.Vh]},zf:function(a){window.___jsl[_.sd.Sh]=a},Po:function(a){window.___jsl[_.sd.Vh]=a}};


}catch(e){_._DumpException(e)}
try{
_.pm=/\s*;\s*/;_.om={get:function(a,c){for(var f=a+"=",g=(window.document.cookie||"").split(_.pm),h=0,k;k=g[h];++h)if(0==k.indexOf(f))return k.substr(f.length);return c}};

}catch(e){_._DumpException(e)}
try{
_.ud=window.oauth2||{};

}catch(e){_._DumpException(e)}
try{
_.vd=function(a){var c=_.wd,f=(0,_.L)("googleapis.config/sessionIndex");f==_.r&&(f=window.__X_GOOG_AUTHUSER);if(f==_.r){var g=window.google;g&&(f=g.authuser)}f==_.r&&(a==_.r&&(a=window.location.href),f=a?c(a,"authuser"):_.r);return f==_.r?_.r:(0,window.String)(f)};_.wd=function(a,c){return(a?_.O.U((0,window.String)(a)):{})[c]||_.r};
_.xd=function(a,c,f){var g=(a=(0,window.String)(a))?_.O.U(a):{};if(g.authuser!=_.r||g.hd!=_.r)return a;c=(0,_.vd)(c);if(f){var g=a,h=g.match(/^((https?:)?\/\/[^\/?#]*)?(\/[^\/?#]+)\/[0-9]+([\/][^?#]*)([?#].*)?$/);if(h&&h[0]){var k=h[1],m=h[4],p=h[5];h[3]=="/"+f&&(g=(k||"")+(m||"/")+(p||""))}if((h=g.match(/^(((https?:)?\/\/[^\/?#]*)([\/][^?#]*)?|([\/][^?#]*))([?#].*)?$/))&&h[0])return k=h[2],a=h[4]||h[5],p=h[6],c!=_.r&&(g=(k||"")+"/"+f+"/"+(0,window.encodeURIComponent)(c)+(a||"/")+(p||"")),g}f=c==
_.r?(0,window.encodeURIComponent)("authuser")+"=0":c.match(/^([-a-z0-9]+[.])+[-a-z0-9]+$/)?[(0,window.encodeURIComponent)("authuser")+"=",(0,window.encodeURIComponent)((0,window.String)(c)),"&"+(0,window.encodeURIComponent)("hd")+"=",(0,window.encodeURIComponent)(c)].join(""):["authuser=",(0,window.encodeURIComponent)(c)].join("");a=a.split("#");c=a[0].indexOf("?");0>c?a[0]=[a[0],"?",f].join(""):(g=[a[0]],c<a[0].length-1&&g.push("&"),g.push(f),a[0]=g.join(""));return g=a.join("#")};
_.yd=_.xd;

}catch(e){_._DumpException(e)}
try{
_.Il=function(a,c){var f={};if(!a)return f;for(var g=a.split(c||"&"),h=0;h<g.length;h++){var k=g[h];k&&(k=k.split("="),f[(0,window.decodeURIComponent)(k[0])]=(0,window.decodeURIComponent)(k[1]))}return f};_.Jl=function(){if(!_.Kl){var a={},c=(0,_.Il)(window.document.cookie,";"),f;for(f in c)0==f.indexOf("oauth2-")&&{}.hasOwnProperty.call(c,f)&&(a[f]=(0,_.Il)(c[f]));_.Ll=a;_.Kl=_.q}}; _.Ml=function(a,c){(0,_.Jl)();var f=_.r;if(a)f=_.Ll["oauth2-"+a]||_.r;else for(var g in _.Ll)if({}.hasOwnProperty.call(_.Ll,g)){f=_.Ll[g]||_.r;break}f&&(f.error&&!c)&&(f=_.r);return f};
_.Ll={};_.Kl=_.t;

}catch(e){_._DumpException(e)}
try{
_.Na=function(a,c){if(!(a<_.Oa)&&_._console$$inline_230)if(2===a&&_._console$$inline_230.warn)_._console$$inline_230.warn(c);else if(3===a&&_._console$$inline_230.error)try{_._console$$inline_230.error(c)}catch(f){}else _._console$$inline_230.log&&_._console$$inline_230.log(c)};_.Pa=function(a){(0,_.Na)(1,a)};
_.Qa=function(a){(0,_.Na)(2,a)};_.Ia=function(a){(0,_.Na)(3,a)};_.Pa.INFO=1;_.Pa.WARNING=2;_.Pa.NONE=4;_.Oa=1;_._console$$inline_230=window.console?window.console:window.opera?window.opera.postError:_.n;

}catch(e){_._DumpException(e)}
try{
_.O=_.O||{};_.O.Sd=function(a,c,f,g){"undefined"!=typeof a.addEventListener?a.addEventListener(c,f,g):"undefined"!=typeof a.attachEvent?a.attachEvent("on"+c,f):(0,_.Qa)("cannot attachBrowserEvent: "+c)};_.O.yo=function(a,c,f,g){a.removeEventListener?a.removeEventListener(c,f,g):a.detachEvent?a.detachEvent("on"+c,f):(0,_.Qa)("cannot removeBrowserEvent: "+c)};


}catch(e){_._DumpException(e)}
try{
_.Wa=function(){function a(){h[0]=1732584193;h[1]=4023233417;h[2]=2562383102;h[3]=271733878;h[4]=3285377520;w=u=0}function c(a){for(var c=m,f=0;64>f;f+=4)c[f/4]=a[f]<<24|a[f+1]<<16|a[f+2]<<8|a[f+3];for(f=16;80>f;f++)c[f]=((c[f-3]^c[f-8]^c[f-14]^c[f-16])<<1|(c[f-3]^c[f-8]^c[f-14]^c[f-16])>>>31)&4294967295;for(var a=h[0],g=h[1],k=h[2],p=h[3],u=h[4],s,w,f=0;80>f;f++)40>f?20>f?(s=p^g&(k^p),w=1518500249):(s=g^k^p,w=1859775393):60>f?(s=g&k|p&(g|k),w=2400959708):(s=g^k^p,w=3395469782),s=((a<<5|a>>>27)&4294967295)+
s+u+w+c[f]&4294967295,u=p,p=k,k=(g<<30|g>>>2)&4294967295,g=a,a=s;h[0]=h[0]+a&4294967295;h[1]=h[1]+g&4294967295;h[2]=h[2]+k&4294967295;h[3]=h[3]+p&4294967295;h[4]=h[4]+u&4294967295}function f(a,f){if("string"===typeof a){for(var a=(0,window.unescape)((0,window.encodeURIComponent)(a)),g=[],h=0,m=a.length;h<m;++h)g.push(a.charCodeAt(h));a=g}f||(f=a.length);g=0;if(0==u)for(;g+64<f;)c(a.slice(g,g+64)),g+=64,w+=64;for(;g<f;)if(k[u++]=a[g++],w++,64==u){u=0;for(c(k);g+64<f;)c(a.slice(g,g+64)),g+=64,w+=64}}
function g(){var a=[],g=8*w;56>u?f(p,56-u):f(p,64-(u-56));for(var m=63;56<=m;m--)k[m]=g&255,g>>>=8;c(k);for(m=g=0;5>m;m++)for(var s=24;0<=s;s-=8)a[g++]=h[m]>>s&255;return a}for(var h=[],k=[],m=[],p=[128],s=1;64>s;++s)p[s]=0;var u,w;a();return{reset:a,update:f,cq:g,Me:function(){for(var a=g(),c="",f=0;f<a.length;f++)c+="0123456789ABCDEF".charAt(window.Math.floor(a[f]/16))+"0123456789ABCDEF".charAt(a[f]%16);return c}}};


}catch(e){_._DumpException(e)}
try{
_.Ya=function(a){var c=(0,_.Wa)();c.update(a);return c.Me()};_.Za=window.crypto;
if(_.Za&&"function"==typeof _.Za.getRandomValues)_.Xa=function(){var a=new window.Uint32Array(1);_.Za.getRandomValues(a);return(0,window.Number)("0."+a[0])};else{_.$a=(0,_.L)("random/maxObserveMousemove");_.$a==_.r&&(_.$a=-1);_.ab=0;_.bb=window.Math.random();_.cb=1;_.eb=1E6*(window.screen.width*window.screen.width+window.screen.height);_.fb=function(a){var a=a||window.event,c=a.screenX+a.clientX<<16,c=c+(a.screenY+a.clientY),c=c*((new window.Date).getTime()%1E6);_.cb=_.cb*c%_.eb;0<_.$a&&++_.ab==_.$a&&
_.O.yo(window,"mousemove",_.fb,_.t)};0!=_.$a&&_.O.Sd(window,"mousemove",_.fb,_.t);_.gb=(0,_.Ya)(window.document.cookie+"|"+window.document.location+"|"+(new window.Date).getTime()+"|"+_.bb);_.Xa=function(){var a=_.cb,a=a+(0,window.parseInt)(_.gb.substr(0,20),16);_.gb=(0,_.Ya)(_.gb);return a/(_.eb+window.Math.pow(16,20))}};
(0,_.M)("shindig.random",_.Xa);

}catch(e){_._DumpException(e)}
try{
_.qm=function(a,c,f,g){for(var h=0;h<_.rm.length;h++){var k=_.rm[h];window.setTimeout(function(){k(a,c,f,g)},1)}};_.sm=function(){var a=window.__OVERRIDE_SID;a==_.r&&(a=_.om.get("SID"));return!!a};
_.tm=function(a,c,f,g){var h=(0,_.um)("proxy");if(f||!h)var h=(0,_.um)("root"),k=(0,_.um)("root-1p")||h,m=(0,_.um)("xd3"),h=(f||(0,window.String)(c?k:h))+m;(c=_.O.U().jsh||_.kb.Ud.yg())&&(h+=(0<=h.indexOf("?")?"&":"?")+"jsh="+(0,window.encodeURIComponent)(c));(0,_.um)("push")&&(h+=(0<=h.indexOf("?")?"&":"?")+"p=1");h+="#parent="+(0,window.encodeURIComponent)(g!=_.r?(0,window.String)(g):_.kb.ma(window.document.location.href));return h+="&rpctoken="+a};
_.vm=function(a,c){var f=(0,_.tm)("",a,c,""),g=_.wm[f];g||(g=(0,_.Wa)(),g.update(f),g=g.Me().toLowerCase(),g+=window.Math.random(),_.wm[f]=g);return"apiproxy"+g};
_.xm=function(a,c,f){function g(a){if(a){h=a.root||h;var a=a.headers,c={SAPISIDHASH:_.q,APISIDHASH:_.q,InterimServerLogin:_.q};if(a&&(a.OriginToken||a.Authorization&&c[(0,window.String)(a.Authorization).split(" ")[0]]))k=_.q}}var h=_.r,k=_.t;if("makeRequest"===a||"listen"===a)g(c);else if("makeHttpRequests"===a&&c){for(var m=(0,_.L)("client/jsonpOverride"),p=0,s=c.length;p<s;++p){var u=c[p];u&&(u=u.params,g(u),m&&(0,_.ym)(u,f))}if(m)return}m=(0,_.vm)(k,h);if(!_.zm[m]){var w=k,A=h,B=(0,window.String)(2147483647*
(0,_.Xa)()|0),p=(0,_.tm)(B,w,A);(0,_.qm)("loading",(new window.Date).getTime(),w,A||_.r);var H=(0,_.vm)(w,A),s=_.O.cg({id:H,name:H});s.style.width="1px";s.style.height="1px";s.style.position="absolute";s.style.top="-100px";if(window.navigator)var u=window.navigator.userAgent||"",I=window.navigator.product||"",u=0!=u.indexOf("Opera")&&-1==u.indexOf("WebKit")&&"Gecko"==I&&0<u.indexOf("rv:1.");else u=_.t;s.src=u?"about:blank":p;window.document.body.appendChild(s);u&&(s.src=p);_.P.N("ready:"+B,function(){_.P.Vb("ready:"+
B);if(!_.Am[H]){_.Am[H]=_.q;var a=_.Bm[H];_.Bm[H]=[];for(var c=0,f=a.length;c<f;++c){var g=a[c];(0,_.xm)(g.Jd,g.Co,g.zc)}(0,_.qm)("ready",(new window.Date).getTime(),w,A||_.r)}});_.P.xc(H,p);_.zm[H]=s}_.Am[m]?_.P.call(m,a,function(c){var g=_.N.parse(c);if("makeRequest"==a&&g){for(var h={},k=0;k<g.length;k++)h[g[k].id]=g[k];f(h,c)}else f(g,c)},c):(_.Bm[m]||(_.Bm[m]=[]),_.Bm[m].push({Jd:a,Co:c,zc:f}))};
_.ym=function(a,c){"GET"!=a.httpMethod&&(0,_.l)("JSONP supports GET methods only.");var f="jpcb"+(0,window.String)(2147483647*(0,_.Xa)()|0),g=window.document.createElement("script"),h=window.document.getElementsByTagName("head")[0];window[f]=function(a){c(a);try{delete window[f]}catch(k){window[f]=_.n}window.setTimeout(function(){h.removeChild(g)},1)};var k=a.root||(0,_.um)("root"),k=k+a.url,m=a.urlParams;if(m)for(var p in m)window.Object.prototype.hasOwnProperty.call(m,p)&&(k=(0,_.Cm)(k,p,m[p]));
k=(0,_.Cm)(k,"callback",f);g.setAttribute("id",f);g.setAttribute("src",k);g.setAttribute("charset","utf-8");h.appendChild(g)};_.Cm=function(a,c,f){a+=0<a.indexOf("?")?"&":"?";return a+=(0,window.encodeURIComponent)(c)+"="+(0,window.encodeURIComponent)(f)};_.um=function(a){return(0,_.L)("googleapis.config/"+a)};_.Dm={};
_.wm={};_.zm={};_.Am={};_.Bm={};_.rm=[];
_.Em={dd:function(a,c){var f=a||{},g=_.kb.ma((0,window.String)(window.location.href));f["X-Origin"]=g;var h=f.Authorization,k=f.OriginToken;if(h==_.r&&k==_.r){if(h==_.r){var m;_.ud&&_.Dm&&(m=(0,_.Ml)());m&&m.access_token&&(h=(0,window.String)(m.token_type||"Bearer")+" "+m.access_token)}if(h==_.r&&(0,_.um)("auth/useFirstPartyAuth")&&(0,_.sm)()){var p=(m=0==g.indexOf("https:")||0==g.indexOf("chrome-extension:"))?"SAPISID":"APISID",k=window[m?"__SAPISID":"__APISID"];k==_.r&&(k=_.om.get(p));k&&(h=f["X-Goog-AuthUser"],
h==_.r&&(h=(0,_.vd)(c)||"0"),f["X-Goog-AuthUser"]=h,h=m?"SAPISIDHASH":"APISIDHASH",m=(0,_.Wa)(),m.update([k,g].join(" ")),h=h+" "+m.Me().toLowerCase())}h==_.r&&((0,_.um)("auth/useInterimAuth")!==_.t&&(0,_.sm)())&&(g=window.__OVERRIDE_SID,g==_.r&&(g=_.om.get("SID")),g&&(h="InterimServerLogin service=google,auth="+g));h?f.Authorization=h:(0,_.um)("auth/useOriginToken")!==_.t&&(g=_.r,(0,_.sm)()&&(g=window.__PVT,g==_.r&&(g=_.om.get("BEAT"))),(k=g)&&(f.OriginToken=k))}return f},Wl:function(a){_.rm.push(a)}, zo:function(a){for(var c=0;c<_.rm.length;c++)if(_.rm[c]==a){_.rm.splice(c,1);break}},Uc:_.xm};


}catch(e){_._DumpException(e)}
try{
_.Qn=window.tamings___||[];_.Rn=window.caja___;_.___=window.___;

}catch(e){_._DumpException(e)}
try{
_.Sn=function(a,c,f){this.method=a;this.transport=c;this.rpc=f};_.J.mh=function(){var a={},c=[];a.execute=function(a){function g(g){g.error&&(h.error=g.error);for(var k=0;k<c.length;k++){var p=c[k].key,s=g[p];s&&(h[p]=s.error?s:s.data||s.result)}m--;0===m&&a(h)}for(var h={},k={},m=0,p=[],s=0;s<c.length;s++){var u=c[s].request.transport;k[u.name]||(p.push(u),m++);k[u.name]=k[u.name]||[];var w=c[s],A={method:w.request.method,id:w.key};w.request.rpc&&(A.params=w.request.rpc);k[u.name].push(A)}for(s=0;s<p.length;s++)p[s].execute(k[p[s].name],g);0==m&&window.setTimeout(function(){a(h)}, 0)};a.add=function(f,g){g&&f&&c.push({key:f,request:g});return a};return a};
_.J.Qf=function(a,c){if("newBatch"!==a){for(var f=a.split("."),g=window.osapi,h=0;h<f.length-1;h++)g[f[h]]=g[f[h]]||{},g=g[f[h]];var k=f[f.length-1];g[k]?(g.__dupwarn||(0,_.Qa)("Skipping duplicate osapi method definition "+a+" on transport "+c.name+"; others may exist, but suppressing warnings"),g.__dupwarn=_.q):(g[k]=function(f){f=f||{};f.userId=f.userId||"@viewer";f.groupId=f.groupId||"@self";return new _.Sn(a,c,f)},"undefined"!==typeof _.Qn&&_.Qn.push(function(){_.Rn.markTameAsFunction(g[k],a)}))}};
_.Sn.prototype.execute=function(a){var c="undefined"!==typeof _.Rn&&_.Rn.getUseless&&_.Rn.getUseless(),f=c?_.Rn.getUseless():this,g=c?_.Rn.untame(a):a,a=_.J.mh();a.add(this.method,this);a.execute(function(a){a.error?g.call(f,a.error):g.call(f,a[f.method])})};


}catch(e){_._DumpException(e)}
try{
_.Tn=function(a,c){for(var f=a.split("."),g=c||window,h;h=f.shift();)if(g[h]!=_.r)g=g[h];else return _.r;return g};_.Un=function(a,c,f){a=a.split(".");f=f||window;!(a[0]in f)&&f.execScript&&f.execScript("var "+a[0]);for(var g;a.length&&(g=a.shift());)!a.length&&c!==_.n?f[g]=c:f=f[g]?f[g]:f[g]={}};
_.Vn=function(a,c){_.J.Qf(a,{name:"googleapis",execute:_.Wn,root:c});var f=(0,_.Tn)(a,window.osapi);(0,_.Un)(a,f);if(0!=a.indexOf("googleapis.")){var g=a.substring(a.indexOf(".")+1),h=g.lastIndexOf(".delete");-1!=h&&h+7==g.length&&(g=g.replace(".delete",".remove"));(0,_.Un)("googleapis."+g,f)}};_.Xn=function(a){for(var c in a)a.hasOwnProperty(c)&&(_.Yn[c]=a[c])};_.Zn=function(a){(0,_.$n)("key",a)};_.$n=function(a,c){c==_.r?(0,_.ao)(a):(_.bo=_.bo||{},_.bo[a]=c)};_.ao=function(a){_.bo&&delete _.bo[a]};
_.co=function(a){a=a||{};if(window.navigator){for(var c=["appVersion","platform","userAgent"],f=[],g=0;g<c.length;g++)window.navigator[c[g]]&&f.push((0,window.encodeURIComponent)(c[g])+"="+(0,window.encodeURIComponent)(window.navigator[c[g]]));a["X-ClientDetails"]=f.join("&")}return a};
_.eo=function(a,c){for(var f=0;f<_.fo.length;f++)window.setTimeout(function(c){return function(){c(a)}}(_.fo[f]),1);return function(){var a=arguments;c.apply(_.r,a);for(var f=0;f<_.go.length;f++)window.setTimeout(function(c){return function(){c.apply(_.r,a)}}(_.go[f]),1)}};_.ho=function(a){a.applicationName=_.io;a.clientVersion="1.0.0-alpha";_.bo&&(a.urlParams=_.bo,_.bo.key&&(a.developerKey=_.bo.key))};
_.Wn=function(a,c){for(var f=this.root||_.r,g=0;g<a.length;g++){var h=a[g],k=h.method.substring(0,h.method.indexOf("."));h.jsonrpc="2.0";h.key=h.id;f=h.root||f;(k=_.Yn[k]||"v1")&&!h.apiVersion&&(h.apiVersion=k)}g={};g=_.Em.dd(g);g=(0,_.co)(g);f={requests:a,headers:g,root:f};(0,_.ho)(f);g=(0,_.eo)(a,c);_.Em.Uc("makeRequest",f,g)};_.jo=function(a){_.fo.push(a)};_.ko=function(a){_.go.push(a)};_.lo=function(a){for(var c=0;c<_.fo.length;c++)if(_.fo[c]==a){_.fo.splice(c,1);break}};
_.mo=function(a){for(var c=0;c<_.go.length;c++)if(_.go[c]==a){_.go.splice(c,1);break}};_.no=function(a,c){for(var f=0,g=a.length;f<g;f++){var h=a[f];h.key=h.id;var k=h.params.headers||{},k=_.Em.dd(k),k=(0,_.co)(k);h.params.headers=k;(0,_.ho)(h.params)}f=(0,_.eo)(a,c);_.Em.Uc("makeHttpRequests",a,f)};
_.oo=function(){var a=_.O.U(),c={debug:"googleapis.config/debug"},f;for(f in c)a[f]&&(0,_.Ba)(c[f],"true"==a[f]);for(var g in(0,_.L)("googleapis.config/methods"))(0,_.Vn)(g);(0,_.L)("googleapis.config/versions")&&(0,_.Xn)((0,_.L)("googleapis.config/versions"));(0,_.L)("googleapis.config/developerKey")&&(0,_.Zn)((0,_.L)("googleapis.config/developerKey"));_.J.Qf("googleapis.newHttpRequest",{name:"googleapis",execute:_.no});(0,_.Un)("googleapis.newHttpRequest",(0,_.Tn)("googleapis.newHttpRequest",window.osapi))}; _.po=function(){this.d={};this.b=_.J.mh()};
_.io=_.r;_.Yn={};_.fo=[];_.go=[];(0,_.oo)();_.po.prototype.add=function(a,c,f){this.d[a]=f;this.b.add(a,c);return this};_.po.prototype.execute=function(a){var c=this;this.b.execute(function(f){var g={},h=_.t,k;for(k in f)if(f.hasOwnProperty(k)){var m=f[k],p=c.d[k];p?p(m):(g[k]=m,h=_.q)}h&&a&&a(g)})};
(0,_.M)("googleapis.ApiClient.register",_.Vn);(0,_.M)("googleapis.ApiClient.setVersions",_.Xn);(0,_.M)("googleapis.ApiClient.setDeveloperKey",_.Zn);(0,_.M)("googleapis.ApiClient.setUrlParameter",_.$n);(0,_.M)("googleapis.ApiClient.removeUrlParameter",_.ao);(0,_.M)("googleapis.ApiClient.addExecuteListener",_.jo);(0,_.M)("googleapis.ApiClient.addResponseListener",_.ko);(0,_.M)("googleapis.ApiClient.removeExecuteListener",_.lo);(0,_.M)("googleapis.ApiClient.removeResponseListener",_.mo);
(0,_.M)("googleapis.ApiClient.init",_.oo);(0,_.M)("googleapis.Batch",_.po);(0,_.M)("googleapis.Batch.prototype.add",_.po.prototype.add);(0,_.M)("googleapis.Batch.prototype.execute",_.po.prototype.execute);(0,_.M)("googleapis.init",function(){(0,_.oo)()});(0,_.M)("googleapis.newBatch",function(){return new _.po});
(0,_.M)("googleapis.newRequest",function(a,c,f){var c=c||{},g={name:"googleapis",execute:_.Wn,root:f},h=_.J.mh(),k=this,f={};f.method=a;f.transport=g;f.rpc=c;f.execute=function(f){h.add(a,{method:a,rpc:c,transport:g});h.execute(function(c){c.error?f.call(k,c.error):f.call(k,c[a])})};return f});(0,_.M)("googleapis.register",function(a,c){(0,_.Vn)(a,c)});(0,_.M)("googleapis.setUrlParameter",function(a,c){(0,_.$n)(a,c)});(0,_.M)("googleapis.removeUrlParameter",function(a){(0,_.ao)(a)});
(0,_.M)("googleapis.setDeveloperKey",function(a){(0,_.Zn)(a)});(0,_.M)("googleapis.setApplicationName",function(a){_.io=a});(0,_.M)("googleapis.setVersions",function(a){(0,_.Xn)(a)});(0,_.M)("googleapis.addExecuteListener",function(a){(0,_.jo)(a)});(0,_.M)("googleapis.removeExecuteListener",function(a){(0,_.lo)(a)});(0,_.M)("googleapis.addResponseListener",function(a){(0,_.ko)(a)});(0,_.M)("googleapis.removeResponseListener",function(a){(0,_.mo)(a)}); (0,_.M)("googleapis.addTransportInitListener",function(a){_.Em.Wl(a)});(0,_.M)("googleapis.removeTransportInitListener",function(a){_.Em.zo(a)});


}catch(e){_._DumpException(e)}
try{
_.Ja={go:{},O:{}};_.Ka={go:{},O:{}};

}catch(e){_._DumpException(e)}
try{


}catch(e){_._DumpException(e)}
try{
_.O=_.O||{};_.O.yd=function(a,c,f){for(var g=[],h=2,k=arguments.length;h<k;++h)g.push(arguments[h]);return function(){for(var f=g.slice(),h=0,k=arguments.length;h<k;++h)f.push(arguments[h]);return c.apply(a,f)}};_.O.se=function(a){var c,f,g={};for(c=0;f=a[c];++c)g[f]=f;return g};


}catch(e){_._DumpException(e)}
try{
_.Ua=_.Ua||{};_.Ua.Zm=function(){var a=0,c=0;window.self.innerHeight?(a=window.self.innerWidth,c=window.self.innerHeight):window.document.documentElement&&window.document.documentElement.clientHeight?(a=window.document.documentElement.clientWidth,c=window.document.documentElement.clientHeight):window.document.body&&(a=window.document.body.clientWidth,c=window.document.body.clientHeight);return{width:a,height:c}};


}catch(e){_._DumpException(e)}
try{
_.Va=function(a,c){window.getComputedStyle(a,"").getPropertyValue(c).match(/^([0-9]+)/);return(0,window.parseInt)(window.RegExp.$1,10)};_.Ua=_.Ua||{};
_.Ua.vg=function(){var a=_.Ua.Zm().height,c=window.document.body,f=window.document.documentElement;if("CSS1Compat"===window.document.compatMode&&f.scrollHeight)return f.scrollHeight!==a?f.scrollHeight:f.offsetHeight;if(0<=window.navigator.userAgent.indexOf("AppleWebKit")){a=0;for(c=[window.document.body];0<c.length;){var g=c.shift(),f=g.childNodes;if("undefined"!==typeof g.style){var h=g.style.overflowY;h||(h=(h=window.document.defaultView.getComputedStyle(g,_.r))?h.overflowY:_.r);if("visible"!=h&&
"inherit"!=h&&(h=g.style.height,h||(h=(h=window.document.defaultView.getComputedStyle(g,_.r))?h.height:""),0<h.length&&"auto"!=h))continue}for(g=0;g<f.length;g++){h=f[g];if("undefined"!==typeof h.offsetTop&&"undefined"!==typeof h.offsetHeight)var k=h.offsetTop+h.offsetHeight+(0,_.Va)(h,"margin-bottom"),a=window.Math.max(a,k);c.push(h)}}return a+(0,_.Va)(window.document.body,"border-bottom")+(0,_.Va)(window.document.body,"margin-bottom")+(0,_.Va)(window.document.body,"padding-bottom")}if(c&&f)return g= f.scrollHeight,h=f.offsetHeight,f.clientHeight!==h&&(g=c.scrollHeight,h=c.offsetHeight),g>a?g>h?g:h:g<h?g:h};


}catch(e){_._DumpException(e)}
try{
_.td=window.iframer=window.iframer||{};_.Q=window.iframes=window.iframes||{};

}catch(e){_._DumpException(e)}
try{
_.Q.D=_.Q.D||{};_.Q.D.Th="friendlyIframe";_.Q.D.em=function(a){try{return!!a.document}catch(c){}return _.t};_.Q.D.jc=function(a){var c=a.parent;return a!=c&&_.Q.D.em(c)?_.Q.D.jc(c):a};_.Q.D.nj=function(a){try{return _.Q.D.jc(a)!=a&&!!a.frameElement&&a.frameElement.name==_.Q.D.Th}catch(c){return _.t}};_.Q.D.Fn=function(a){var c=a.userAgent||"",a=a.product||"";return 0!=c.indexOf("Opera")&&-1==c.indexOf("WebKit")&&"Gecko"==a&&0<c.indexOf("rv:1.")};
if(window.ToolbarApi)_.Ad=window.ToolbarApi,_.Ad.ha=window.ToolbarApi.getInstance,_.Ad.prototype=window.ToolbarApi.prototype,_.C=_.Ad.prototype,_.C.Oj=_.Ad.prototype.openWindow,_.C.qi=_.Ad.prototype.closeWindow,_.C.rk=_.Ad.prototype.setOnCloseHandler,_.C.ni=_.Ad.prototype.canClosePopup,_.C.ck=_.Ad.prototype.resizeWindow;else{_.Bd=_.r;_.Ad=(0,_.v)();_.Ad.ha=function(){!_.Bd&&(window.external&&window.external.GTB_IsToolbar)&&(_.Bd=new _.Ad);return _.Bd};_.C=_.Ad.prototype;_.C.Oj=function(a){return window.external.GTB_OpenPopup&&
window.external.GTB_OpenPopup(a)};_.C.qi=function(a){window.external.GTB_ClosePopupWindow&&window.external.GTB_ClosePopupWindow(a)};_.C.rk=function(a,c){window.external.GTB_SetOnCloseHandler&&window.external.GTB_SetOnCloseHandler(a,c)};_.C.ni=function(a){return window.external.GTB_CanClosePopup&&window.external.GTB_CanClosePopup(a)};_.C.ck=function(a,c){return window.external.GTB_ResizeWindow&&window.external.GTB_ResizeWindow(a,c)};window.ToolbarApi=_.Ad;window.ToolbarApi.getInstance=_.Ad.ha};
if(!window.iframes||!window.iframes.open){_.Dd=/^[-_.0-9A-Za-z]+$/;_.Ed={open:"open",onready:"ready",close:"close",onresize:"resize",onOpen:"open",onReady:"ready",onClose:"close",onResize:"resize",onRenderStart:"renderstart"};_.Fd={onBeforeParentOpen:"beforeparentopen"};_.Gd={longdesc:_.q,name:_.q,src:_.q,frameborder:_.q,marginwidth:_.q,marginheight:_.q,scrolling:_.q,align:_.q,height:_.q,width:_.q,id:_.q,"class":_.q,style:_.q,title:_.q,tabindex:_.q,hspace:_.q,vspace:_.q,allowtransparency:_.q};_.Hd=
{onOpen:function(a){var c=a.ba();a.Ma(c.container||c.element);return a},onClose:function(a){a.remove()}};_.Id=window.encodeURIComponent||window.escape;_.Jd=function(a){(0,_.Ia)(a.join(""))};_.Kd=function(){_.Q.kj++;return["I",_.Q.kj,"_",(new window.Date).getTime()].join("")};_.Ld=function(a){var c={allowtransparency:"true",frameborder:0,hspace:0,marginheight:0,marginwidth:0,scrolling:"no",style:"",tabindex:"0",vspace:0,width:"100%"},f;for(f in a)a.hasOwnProperty(f)&&(c[f]=a[f]);return c};_.Nd=function(a,
c,f){f=f||{};f.id||(f.id=a);f.name||(f.name=a);f.src||(f.src=c);a=(0,_.Ld)(f);c=[];c.push("<iframe ");for(var g in a)a.hasOwnProperty(g)&&(_.Gd[g.toLowerCase()]?(f=(0,window.String)(a[g]),c.push(g),c.push('="'),c.push(_.O.Yd("style"==g.toLowerCase()?(0,_.Md)(f):f)),c.push('" ')):(0,_.Jd)(['Iframe attribute "',g,'" not allowed.']));c.push("></iframe>");return c.join("")};_.Md=function(a){if(!a)return"";for(var c=[],a=a.split(";"),f=0,g=a.length;f<g;++f){var h=a[f];0==h.length&&f+1==g||(h=h.split(":"),
2==h.length&&h[0].match(/^[ a-zA-Z_-]+$/)&&h[1].match(/^[ +.%0-9a-zA-Z_-]+$/)?c.push(h.join(":")):(0,_.Jd)(['Iframe style "',a[f],'" not allowed.']))}return c.join(";")};_.Od=function(a){if(0==a.indexOf("http:")||0==a.indexOf("https:")||0==a.indexOf("javascript:"))return a;if(0==a.indexOf("//"))return window.location.protocol+a;if(0==a.indexOf("/"))return window.location.protocol+"//"+window.location.host+a;var c=window.location.protocol+"//"+window.location.host+window.location.pathname;return c.substring(0,
c.lastIndexOf("/")+1)+a};_.Pd=function(a){return a instanceof window.Array?a.join(","):a instanceof window.Object?_.N.stringify(a):a};_.Qd=function(a,c,f){var g={},h=a.indexOf("#");-1==h?(g.hash=_.r,g.gd=a):(g.hash=a.substring(h+1),g.gd=a.substring(0,h));a=g.gd.indexOf("?");-1==a?g.Ed=_.r:(g.Ed=g.gd.substring(a+1),g.gd=g.gd.substring(0,a));var a=f?g.hash?[g.hash]:[]:g.Ed?[g.Ed]:[],k;for(k in c)c.hasOwnProperty(k)&&(h=(0,_.Pd)(c[k]),a.push([(0,_.Id)(k),(0,_.Id)(h)].join("=")));f?g.hash=a.join("&"):
g.Ed=a.join("&");return g.gd+(g.Ed?"?"+g.Ed:"")+(g.hash?"#"+g.hash:"")};_.Rd=(0,_.v)();_.Sd=function(){var a=(0,_.vd)();return a!==_.n&&a!==_.r&&""!==a?"u/"+a+"/":""};_.Td=function(a){var c=_.O.U().jsh||_.kb.Ud.yg();!a.jsh&&c&&(a.jsh=c);c=_.O.U()._bsh||_.kb.Ud.Bm();!a._bsh&&c&&(a._bsh=c)};_.Ud=function(a){a&&a.match(_.Dd)&&(0,_.Ba)("googleapis.config/gcv",a)};_.Vd=function(a){_.kb.Ud.Po(a)};_.Wd=function(a){_.kb.Ud.zf(a)};_.Xd=function(a,c){var f=c||{},g;for(g in a)a.hasOwnProperty(g)&&(f[g]=a[g]);
return f};_.Yd=function(a){_.Q.wf[a]||(_.Q.wf[a]={},_.P.N(a,function(c,f){var g=this.f;if("string"==typeof c&&!(c in{})&&!(g in{})){var h=this.callback,k=_.Q.wf[a][g],m;k&&window.Object.hasOwnProperty.call(k,c)?m=k[c]:window.Object.hasOwnProperty.call(_.Q.td,a)&&(m=_.Q.td[a]);if(m)return g=window.Array.prototype.slice.call(arguments,1),m._iframe_wrapped_rpc_&&h&&g.push(h),m.apply({},g)}(0,_.Jd)(['Unregistered call in window "',window.name,'" for method "',a,'", via proxyId "',c,'" from frame "',g,
'".']);return _.r}));return _.Q.wf[a]};_.Zd=function(a,c,f,g,h){var k=[],m;for(m in a)if(a.hasOwnProperty(m)){var p=c,s=f,u=a[m],w=g,A=(0,_.Yd)(m);A[p]=A[p]||{};w=_.O.yd(w,u);u._iframe_wrapped_rpc_&&(w._iframe_wrapped_rpc_=_.q);A[p][s]=w;k.push(m)}if(h)for(m in _.Q.td)_.Q.td.hasOwnProperty(m)&&k.push(m);return k.join(",")};_.$d=function(a,c,f){function g(g){var k=window.Array.prototype.slice.call(arguments,0),m=k[k.length-1];if("function"===typeof m){var p=m;k.pop()}k.unshift(c,a,p,f);var s;a:if(".."==
c||window.document.getElementById(c))s=window;else{for(m=0;m<_.Q.pg.length;m++)try{var u=_.Q.pg[m];if(u&&u.document&&(u.document||window.document).getElementById(c)){s=u;break a}}catch(w){}s=_.r}s?s==window?_.P.call.apply(_.P,k):(s=s.gadgets.rpc,s.call.apply(s,k)):(0,_.Jd)(["RPC ",a,' not sent: target iframe "',c,'" not found.'])}g._iframe_wrapped_rpc_=_.q;return g};_.ae=function(a,c,f){var g={};if(a&&a._methods)for(var a=a._methods.split(","),h=0;h<a.length;h++){var k=a[h];g[k]=(0,_.$d)(k,c,f)}return g};
_.be=function(a){return a&&a.disableMultiLevelParentRelay?_.t:_.td&&_.td._open&&"inline"!=a.style&&a.inline!==_.q&&!(a.container&&("string"==typeof a.container&&window.document.getElementById(a.container)||window.document==(a.container.ownerDocument||a.container.document)))};_.ce=function(a){a&&a.parentNode&&a.parentNode.removeChild(a)};_.de=function(a,c){function f(){}f.prototype=c.prototype;a.prototype=new f};_.ee=function(a,c,f,g,h,k,m,p){if(":"==a.charAt(0)){var a="iframes/"+a.substring(1),s=
a+"/params",u={},w=(0,_.L)(s);(0,_.Ba)(s,w||u);s=a+"/url";u=(u=(0,_.L)(a+"/url"))||"";u=u.replace(/:session_prefix:/g,(0,_.Sd)());u=u.replace(/:session_index:/g,(0,_.vd)()||"0");u=u.replace(/:socialhost:/g,(0,_.L)("iframes/:socialhost:"));(0,_.Ba)(s,(0,_.Od)(u));a=(0,_.L)(a)}else a={url:(0,_.Od)(a)};this.fa=a;this.openParams=this.o=c;this.pb=f||{};this.Ua=g;this.i=_.t;this.Vn(c.style);this.d={};this.Sc(function(){this.Vl(h);k&&this.Rf("close",k)});this.Rb=this.ac=m;this.vh=(p||[]).slice();m&&this.vh.unshift(m.W())};
_.C=_.ee.prototype;_.C.ba=(0,_.x)("o");_.C.Oa=(0,_.x)("pb");_.C.Mb=(0,_.x)("Ua");_.C.ya=(0,_.x)("Rb");_.C.Vn=function(a){if(!this.i)if(a=a&&!_.Q.Be[a]&&_.Q.dg[a]){this.j=[];var c=this;a(function(){c.i=_.q;for(var a=0,g=c.j.length;a<g;++a)c.j[a].call(c)})}else this.i=_.q};_.C.Sc=function(a){this.i?a.call(this):this.j.push(a)};_.C.Vl=function(a){var c=this.Im();if(c){if("function"===typeof c)c=c(this);else{var f={},g;for(g in c){var h=c[g];f[g]="function"===typeof h?_.O.yd(c,h,this):h}c=f}for(var k in a)f=
c[k],"function"===typeof f&&this.Rf(a[k],_.O.yd(c,f))}};_.C.Y=function(a,c){this.Sc(function(){this.Rf(a,c)})};_.C.Rf=function(a,c){this.d[a]=this.d[a]||[];this.d[a].push(c)};_.C.zb=function(a,c){this.Sc(function(){var f=this.d[a];if(f)for(var g=0,h=f.length;g<h;++g)if(f[g]===c){f.splice(g,1);break}})};_.C.kb=function(a,c){var f,g=this.d[a];if(g)for(var h=window.Array.prototype.slice.call(arguments,1),k=0,m=g.length;k<m;++k)try{f=g[k].apply({},h)}catch(p){(0,_.Jd)(['Exception when calling callback "',
a,'" with exception "',p.name,": ",p.message,'".'])}return f};_.C.Im=function(){var a=this.o.style;return a&&_.Q.Be[a]?_.Q.Be[a]:a?((0,_.Qa)(['Missing handler for style "',a,'". Continuing with default handler.'].join("")),_.r):_.Hd};_.C.Te=function(a){return"number"==typeof a?{value:a,Ec:a+"px"}:"100%"==a?{value:100,Ec:"100%",tj:_.q}:_.r};_.S=function(a,c,f,g,h,k,m){_.ee.call(this,a,c,f,g,_.Ed,h,k,m);this.id=c.id||(0,_.Kd)();this.ip=!!c.rpcToken;this.Ch=c.rpcToken||window.Math.round(1E9*(0,_.Xa)());
var a=this.pb,c={},f=this.fa.params||{},p;for(p in a)"#"==p.charAt(0)&&(c[p.substring(1)]=a[p]),0==p.indexOf("fr-")&&(c[p.substring(3)]=a[p]),"#"==f[p]&&(c[p]=a[p]);for(var s in c)delete a["fr-"+s],delete a["#"+s],delete a[s];this.Gn=c;this.jg={};this.Sc(function(){this.kb("open");(0,_.Xd)(this.jg,this)})};(0,_.de)(_.S,_.ee);_.C=_.S.prototype;_.C.Ma=function(a,c){if(!this.fa.url)return(0,_.Jd)(["Cannot open iframe, empty URL."]),this;var f=window.location.protocol+"//"+window.location.host,g=this.id;
(0,_.Td)(this.pb);var h=(0,_.Xd)(this.Ua);h._ready=this.of;h._close=this.close;h._open=this.Pj;h._resizeMe=this.dk;h._renderstart=this.Lj;var k=this.Gn;k.id=g;k.parent=f;k.rpctoken=this.Ch;k._methods=(0,_.Zd)(h,g,"",this,_.q);f=this.hp();f=(0,_.Qd)(f,k,_.q);a="string"===typeof a?window.document.getElementById(a):a;if(this.ba().allowPost&&2E3<f.length)this.po(a,g,k,c);else if(this.ip)a.innerHTML=(0,_.Nd)(g,f,c);else if(_.Q.D.Fn(window.navigator||{})){a.innerHTML=(0,_.Nd)(g,"about:blank",c);a.firstChild.src=
f;try{a.firstChild.contentDocument.location.href=f}catch(m){}}else{k=(0,_.Nd)(g,f,c);try{a.innerHTML=k}catch(p){h=window.document.createElement("div");for(h.innerHTML=k;a.firstChild;)a.removeChild(a.firstChild);a.appendChild(h.firstChild)}}this.Cc=a;this.lb=a.firstChild;_.Q.Nc[g]=this;_.P.Vc(g,this.Ch);_.P.Wc(g,f);return this};_.C.am=function(a){var c=a.id,f=a.src,g=/#(?:.*&)?rpctoken=(\d+)/.exec(f),g=g&&g[1];this.id=c;this.Ch=g;this.Cc=a.parentNode;this.lb=a;_.Q.Nc[c]=this;a=(0,_.Xd)(this.Ua);a._ready=
this.of;a._close=this.close;a._open=this.Pj;a._resizeMe=this.dk;a._renderstart=this.Lj;(0,_.Zd)(a,c,"",this,_.q);_.P.Vc(c,g);_.P.Wc(c,f);return this};_.C.$l=function(a){var a=(0,_.Ld)(a||{}),c;for(c in a)window.Object.prototype.hasOwnProperty.call(a,c)&&("style"==c?this.lb.style.cssText=a[c]:this.lb.setAttribute(c,a[c]))};_.C.po=function(a,c,f,g){a.innerHTML=(0,_.Nd)(c,"",g);var h;-1!=window.navigator.userAgent.indexOf("WebKit")&&(h=a.firstChild,g=(0,_.Nd)(c+"_inner","",{style:"display:none"}),h=
h.contentWindow.document,h.open(),h.write(g));g=(0,_.Qd)(this.fa.url,f,_.q);f=this.pb||{};g={action:g,method:"POST",target:c};c=window.document.createElement("form");c.style.display="none";for(var k in g)g.hasOwnProperty(k)&&(c[k]=g[k]);for(var m in f)f.hasOwnProperty(m)&&(k=window.document.createElement("input"),k.type="hidden",k.name=m,k.value=f[m],c.appendChild(k));a.appendChild(c);c.submit();c.parentNode.removeChild(c);h&&h.close()};_.C.Ra=function(a,c){this.jg[a]=c};_.C.W=(0,_.x)("id");_.C.ca=
(0,_.x)("lb");_.C.Q=(0,_.x)("Cc");_.C.Cb=(0,_.ba)("Cc");_.C.of=function(a){var c=(0,_.ae)(a,this.id,"");this.Rb&&"function"==typeof this.Ua._ready&&(a._methods=(0,_.Zd)(c,this.Rb.W(),this.id,this,_.t),this.Ua._ready(a));(0,_.Xd)(a,this);(0,_.Xd)(c,this);this.kb("ready",a)};_.C.Lj=function(a){this.kb("renderstart",a)};_.C.wo=function(a,c,f){f._methods=(0,_.Zd)((0,_.ae)(f,a,""),this.id,a,this,_.t);c(f)};_.C.close=function(a){a=this.kb("close",a);if(_.Q.D.nj(window)){var c=window.frameElement,f=c.parentNode;
"friendlyIframeContainer"==f.className?(0,_.ce)(f):(0,_.ce)(c)}delete _.Q.Nc[this.id];return a};_.C.remove=function(){(0,_.ce)(window.document.getElementById(this.id))};_.C.Pj=function(a){var c=(0,_.ae)(a.params,this.id,a.proxyId);delete a.params._methods;"_parent"==a.openParams.anchor&&(a.openParams.anchor=this.Cc);if((0,_.be)(a.openParams))new _.fe(a.url,a.openParams,a.params,c,c._onclose,this,a.openedByProxyChain);else if("expandable"===a.openParams.style&&a.openParams.inline!==_.q&&_.Q.D.jc(window)!=
window)this.oo(a,c);else{var f=new _.S(a.url,a.openParams,a.params,c,c._onclose,this,a.openedByProxyChain),g=this;f.Sc(function(){var a=g.li(f);c._onopen(a)})}};_.C.oo=function(a,c){var f=_.Q.D.jc(window),g={height:0,name:_.Q.D.Th,style:"left:0;position:absolute;top:0;z-index:-10000",width:0},h=f.document.createElement("ins");h.className="friendlyIframeContainer";h.innerHTML=(0,_.Nd)("","about:blank",g);f.document.body.appendChild(h);f=h.firstChild.contentWindow;_.Q.pg.push(f);g=f.document;h=['<html><body><script src="',
_.Q.ug(),'"><\/script></body></html>'].join("");g.open();g.write(h);g.close();g=a.openParams.id||(0,_.Kd)();a.openParams.id=g;g=_.O.yd(this,this.wo,g,c._ready);c._ready=g;var k=_.O.yd(f,function(f,g){if(!f.le||"function"!=typeof f.le.open)return _.t;var h=f.le.open(a.url,a.openParams,a.params,c,c._onclose,g),h=g.li(h);c._onopen(h);return _.q},f,this),m=window.setInterval(function(){k()&&window.clearInterval(m)},10)};_.C.li=function(a){var c={childId:a.W()},f=a.jg;f._toclose=a.close;c._methods=(0,_.Zd)(f,
this.id,a.id,a,_.t);return c};_.C.dk=function(a){if(this.kb("resize",a)===_.n&&this.lb){var c=this.Te(a.width);c!=_.r&&(this.lb.style.width=c.Ec);a=this.Te(a.height);a!=_.r&&(this.lb.style.height=a.Ec);if(this.lb.parentElement&&(c!=_.r&&c.tj||a!=_.r&&a.tj))this.lb.parentElement.style.display="block"}};_.C.hp=function(){return(0,_.Qd)(this.fa.url,this.pb,_.t)};_.fe=function(a,c,f,g,h,k,m){_.ee.call(this,a,c,f,g,_.Fd,h,k,m);this.url=a;this.b=_.r;this.G=(0,_.Kd)();this.Sc(function(){this.kb("beforeparentopen");
var a=(0,_.Xd)(this.Ua);a._onopen=this.J;a._ready=this.of;a._onclose=this.F;this.pb._methods=(0,_.Zd)(a,"..",this.G,this,_.q);var a={},c;for(c in this.pb)a[c]=(0,_.Pd)(this.pb[c]);_.td._open({url:this.fa.url,openParams:this.o,params:a,proxyId:this.G,openedByProxyChain:this.vh})})};(0,_.de)(_.fe,_.ee);_.fe.prototype.Gi=(0,_.x)("b");_.fe.prototype.J=function(a){this.b=a.childId;var c=(0,_.ae)(a,"..",this.b);(0,_.Xd)(c,this);this.close=c._toclose;_.Q.Nc[this.b]=this;this.Rb&&this.Ua._onopen&&(a._methods=
(0,_.Zd)(c,this.Rb.W(),this.b,this,_.t),this.Ua._onopen(a))};_.fe.prototype.of=function(a){var c=(0,window.String)(this.b),f=(0,_.ae)(a,"..",c);(0,_.Xd)(a,this);(0,_.Xd)(f,this);this.kb("ready",a);this.Rb&&this.Ua._ready&&(a._methods=(0,_.Zd)(f,this.Rb.W(),c,this,_.t),this.Ua._ready(a))};_.fe.prototype.F=function(a){if(this.Rb&&this.Ua._onclose)this.Ua._onclose(a);else return a=this.kb("close",a),delete _.Q.Nc[this.b],a};_.ge=function(a,c,f,g,h,k,m){_.ee.call(this,a,c,f,g,_.Fd,k,m);this.X=h;g._close=
this.close;this.onClosed=this.b;this.z=0;this.Sc(function(){this.kb("beforeparentopen");var a=(0,_.Xd)(this.Ua);this.pb._methods=(0,_.Zd)(a,"..",this.G,this,_.q);(0,_.Td)(this.pb);var a=(0,_.Qd)(this.fa.url,this.pb,_.t),c=h.Oj(a);this.canAutoClose=function(a){a(h.ni(c))};h.rk(c,this);this.z=c})};(0,_.de)(_.ge,_.ee);_.ge.prototype.close=function(a){a=this.kb("close",a);this.X.qi(this.z);return a};_.ge.prototype.b=function(){this.kb("close")};_.he=function(a){return _.Q.Be[a]};_.ie=function(a,c){_.Q.Be[a]=
c};_.je=function(a){a=a||{};"auto"===a.height&&(a.height=_.Ua.vg());var c=window&&_.Ad&&_.Ad.ha();c?c.ck(a.width||0,a.height||0):_.td&&_.td._resizeMe&&_.td._resizeMe(a)};_.ke=function(a){(0,_.Ud)(a)};_.Cd=function(){function a(a){var c=_.t;try{if(a!=_.r)var f=window.parent.frames[a.id],c=f.iframer.id==a.id&&f.iframes.openedId_(_.td.id)}catch(m){}try{_.Q.rf={origin:this.origin,referer:this.referer,claimedOpenerId:a&&a.id,claimedOpenerProxyChain:a&&a.proxyChain||[],sameOrigin:c};for(a=0;a<_.Q.qf.length;++a)_.Q.qf[a](_.Q.rf);
_.Q.qf=[]}catch(p){}}_.Q.Nc={};_.Q.Be={};_.Q.dg={};_.Q.kj=0;_.Q.pg=[];_.Q.wf={};_.Q.td={};_.Q.rf=_.r;_.Q.qf=[];_.P.N("_noop_echo",function(){var a=_.Q.Nc[this.f],c=a&&a.Rb,f=_.r;c&&(f={},f.id=c.W(),f.proxyChain=a.vh);this.callback(f)});if(window.parent!=window){var c=_.O.U();c.gcv&&(0,_.Ud)(c.gcv);var f=c.jsh;f&&(0,_.Vd)(f);(0,_.Xd)((0,_.ae)(c,"..",""),_.td);(0,_.Xd)(c,_.td);window.setTimeout(function(){_.P.call("..","_noop_echo",a)},0)}_.Q.aa=_.he;_.Q.ja=_.ie;_.Q.nk=_.ke;_.Q.Ub=_.je;_.Q.Ei=function(a){return _.Q.dg[a]};
_.Q.Af=function(a,c){_.Q.dg[a]=c};_.Q.bk=_.je;_.Q.wk=_.ke;_.Q.Qb={};_.Q.Qb.get=_.he;_.Q.Qb.set=_.ie;_.Q.ei=function(a,c){(0,_.Yd)(a);_.Q.td[a]=c||window[a]};_.Q.dq=function(a){delete _.Q.td[a]};_.Q.open=function(a,c,f,m,p,s){3==arguments.length?m={}:4==arguments.length&&"function"===typeof m&&(p=m,m={});var u="bubble"===c.style&&_.Ad&&_.Ad.ha();return u?new _.ge(a,c,f,m,u,p,s):(0,_.be)(c)?new _.fe(a,c,f,m,p,s):new _.S(a,c,f,m,p,s)};_.Q.close=function(a,c){_.td&&_.td._close&&_.td._close(a,c)};_.Q.yb=
function(a,c,f){2==arguments.length&&"function"===typeof p&&(f=c,c={});var m=a||{};"height"in m||(m.height=_.Ua.vg());var p=c||{};m._methods=(0,_.Zd)(p,"..","",_.td,_.q);_.td&&_.td._ready&&_.td._ready(m,f)};_.Q.zg=function(a){_.Q.rf?a(_.Q.rf):_.Q.qf.push(a)};_.Q.mi=function(a,c,f){var m=window.Array.prototype.slice.call(arguments);_.Q.zg(function(a){a.sameOrigin&&(m.unshift("/"+a.claimedOpenerId+"|"+window.location.protocol+"//"+window.location.host),_.P.call.apply(_.P,m))})};_.Q.Qj=function(a){return!!_.Q.Nc[a]};
_.Q.ug=function(){return["https://ssl.gstatic.com/gb/js/",(0,_.L)("googleapis.config/gcv")].join("")};_.Q.Vj=function(a){var c={mouseover:1,mouseout:1};if(_.td._event)for(var f=0;f<a.length;f++){var m=a[f];m in c&&_.O.Sd(window.document,m,function(a){_.td._event({event:a.type,timestamp:(new window.Date).getTime()})},_.q)}};_.Q.pk=_.Vd;_.Q.zf=_.Wd;_.Q.Wn=_.Rd;_.Q.mj=_.td};(0,_.Cd)()}else _.Q.ei=_.Q.allow,_.Q.mi=_.Q.callSiblingOpener,_.Q.close=_.Q.close,_.Q.ug=_.Q.getGoogleConnectJsUri,_.Q.aa=_.Q.getHandler,
_.Q.Ei=_.Q.getDeferredHandler,_.Q.zg=_.Q.getParentInfo,_.Q.mj=_.Q.iframer,_.Q.open=_.Q.open,_.Q.Qj=_.Q.openedId_,_.Q.Vj=_.Q.propagate,_.Q.yb=_.Q.ready,_.Q.Ub=_.Q.resize,_.Q.nk=_.Q.setGoogleConnectJsVersion,_.Q.pk=_.Q.setJsHint,_.Q.zf=_.Q.setBootstrapHint,_.Q.ja=_.Q.setHandler,_.Q.Af=_.Q.setDeferredHandler,_.ee=window.IframeBase,_.ee.prototype=window.IframeBase.prototype,_.C=_.ee.prototype,_.C.Y=_.ee.prototype.addCallback,_.C.Mb=_.ee.prototype.getMethods,_.C.ya=_.ee.prototype.getOpenerIframe,_.C.ba=
_.ee.prototype.getOpenParams,_.C.Oa=_.ee.prototype.getParams,_.C.zb=_.ee.prototype.removeCallback,_.S=window.Iframe,_.S.prototype=window.Iframe.prototype,_.C=_.S.prototype,_.C.close=_.S.prototype.close,_.C.Ra=_.S.prototype.exposeMethod,_.C.W=_.S.prototype.getId,_.C.ca=_.S.prototype.getIframeEl,_.C.Q=_.S.prototype.getSiteEl,_.C.Ma=_.S.prototype.openInto,_.C.remove=_.S.prototype.remove,_.C.Cb=_.S.prototype.setSiteEl,_.C.Y=_.S.prototype.addCallback,_.C.Mb=_.S.prototype.getMethods,_.C.ya=_.S.prototype.getOpenerIframe,
_.C.ba=_.S.prototype.getOpenParams,_.C.Oa=_.S.prototype.getParams,_.C.zb=_.S.prototype.removeCallback,_.fe=window.IframeProxy,_.fe.prototype=window.IframeProxy.prototype,_.C=_.fe.prototype,_.C.Gi=_.fe.prototype.getTargetIframeId,_.C.Y=_.fe.prototype.addCallback,_.C.Mb=_.fe.prototype.getMethods,_.C.ya=_.fe.prototype.getOpenerIframe,_.C.ba=_.fe.prototype.getOpenParams,_.C.Oa=_.fe.prototype.getParams,_.C.zb=_.fe.prototype.removeCallback,window.IframeWindow&&(_.ge=window.IframeWindow,_.ge.prototype=window.IframeWindow.prototype, _.ge.prototype.close=_.ge.prototype.close,_.ge.prototype.b=_.ge.prototype.onClosed),_.Q.Qb=window.iframes.handlers,_.Q.Qb.get=_.Q.Qb.get,_.Q.Qb.set=_.Q.Qb.set,_.Q.bk=_.Q.resizeMe,_.Q.wk=_.Q.setVersionOverride;
(0,_.M)("iframes.allow",_.Q.ei);(0,_.M)("iframes.callSiblingOpener",_.Q.mi);(0,_.M)("iframes.close",_.Q.close);(0,_.M)("iframes.getGoogleConnectJsUri",_.Q.ug);(0,_.M)("iframes.getHandler",_.Q.aa);(0,_.M)("iframes.getDeferredHandler",_.Q.Ei);(0,_.M)("iframes.getParentInfo",_.Q.zg);(0,_.M)("iframes.iframer",_.Q.mj);(0,_.M)("iframes.open",_.Q.open);(0,_.M)("iframes.openedId_",_.Q.Qj);(0,_.M)("iframes.propagate",_.Q.Vj);(0,_.M)("iframes.ready",_.Q.yb);(0,_.M)("iframes.resize",_.Q.Ub);
(0,_.M)("iframes.setGoogleConnectJsVersion",_.Q.nk);(0,_.M)("iframes.setBootstrapHint",_.Q.zf);(0,_.M)("iframes.setJsHint",_.Q.pk);(0,_.M)("iframes.setHandler",_.Q.ja);(0,_.M)("iframes.setDeferredHandler",_.Q.Af);(0,_.M)("IframeBase",_.ee);(0,_.M)("IframeBase.prototype.addCallback",_.ee.prototype.Y);(0,_.M)("IframeBase.prototype.getMethods",_.ee.prototype.Mb);(0,_.M)("IframeBase.prototype.getOpenerIframe",_.ee.prototype.ya);(0,_.M)("IframeBase.prototype.getOpenParams",_.ee.prototype.ba);
(0,_.M)("IframeBase.prototype.getParams",_.ee.prototype.Oa);(0,_.M)("IframeBase.prototype.removeCallback",_.ee.prototype.zb);(0,_.M)("Iframe",_.S);(0,_.M)("Iframe.prototype.close",_.S.prototype.close);(0,_.M)("Iframe.prototype.exposeMethod",_.S.prototype.Ra);(0,_.M)("Iframe.prototype.getId",_.S.prototype.W);(0,_.M)("Iframe.prototype.getIframeEl",_.S.prototype.ca);(0,_.M)("Iframe.prototype.getSiteEl",_.S.prototype.Q);(0,_.M)("Iframe.prototype.openInto",_.S.prototype.Ma);
(0,_.M)("Iframe.prototype.remove",_.S.prototype.remove);(0,_.M)("Iframe.prototype.setSiteEl",_.S.prototype.Cb);(0,_.M)("Iframe.prototype.addCallback",_.S.prototype.Y);(0,_.M)("Iframe.prototype.getMethods",_.S.prototype.Mb);(0,_.M)("Iframe.prototype.getOpenerIframe",_.S.prototype.ya);(0,_.M)("Iframe.prototype.getOpenParams",_.S.prototype.ba);(0,_.M)("Iframe.prototype.getParams",_.S.prototype.Oa);(0,_.M)("Iframe.prototype.removeCallback",_.S.prototype.zb);(0,_.M)("IframeProxy",_.fe);
(0,_.M)("IframeProxy.prototype.getTargetIframeId",_.fe.prototype.Gi);(0,_.M)("IframeProxy.prototype.addCallback",_.fe.prototype.Y);(0,_.M)("IframeProxy.prototype.getMethods",_.fe.prototype.Mb);(0,_.M)("IframeProxy.prototype.getOpenerIframe",_.fe.prototype.ya);(0,_.M)("IframeProxy.prototype.getOpenParams",_.fe.prototype.ba);(0,_.M)("IframeProxy.prototype.getParams",_.fe.prototype.Oa);(0,_.M)("IframeProxy.prototype.removeCallback",_.fe.prototype.zb);(0,_.M)("IframeWindow",_.ge);
(0,_.M)("IframeWindow.prototype.close",_.ge.prototype.close);(0,_.M)("IframeWindow.prototype.onClosed",_.ge.prototype.b);(0,_.M)("iframes.util.getTopMostAccessibleWindow",_.Q.D.jc);(0,_.M)("iframes.handlers.get",_.Q.Qb.get);(0,_.M)("iframes.handlers.set",_.Q.Qb.set);(0,_.M)("iframes.resizeMe",_.Q.bk);(0,_.M)("iframes.setVersionOverride",_.Q.wk);


}catch(e){_._DumpException(e)}
try{
_.me=function(a,c,f){return a[c]=a[c]||f};_.ne=function(a){a=a.style;a.textIndent="0";a.margin="0";a.padding="0";a.background="transparent";a.borderStyle="none";a.cssFloat="none";a.styleFloat="none";a.lineHeight="normal";a.fontSize="1px";a.verticalAlign="baseline"};_.oe=function(a){var c=a.clientWidth;return"position:absolute;top:-10000px;width:"+(c?c+"px":a.style.width||"300px")+";margin:0px;border-style:none;"};
_.pe=function(a,c){var f={};f.width=c?c.width:a.width;f.height=c?c.height:a.height;var g=a.ca(),h=g.parentNode,k=f.width,f=f.height;(0,_.ne)(h);h.style.display="inline-block";g=g.style;g.position="static";g.left=0;g.top=0;g.visibility="visible";k&&(g.width=k+"px");f&&(g.height=f+"px");(k=c?c.title:_.r)&&a.ca().setAttribute("title",k)};
_.qe=window;_.re=window.document;(0,_.me)(_.qe,"gapi",{});_.se={open:function(a){var c=window.document.getElementById(a.ba().container);return a.Ma(c,{style:(0,_.oe)(c,a)})},attach:function(a,c){var f=window.document.getElementById(a.ba().container);a.am(c);a.$l({style:(0,_.oe)(f,a)})}};_.se.onready=_.pe;_.se.onRenderStart=_.pe;_.se.close=function(a){var c=a.Q();c&&c.removeChild(a.ca())};_.Q.ja("inline",_.se);


}catch(e){_._DumpException(e)}
try{
_.te=function(a,c){this.b=a;this.bc=c};_.ue=function(a){this.w=this.Ib=a;this.n=_.r;this.slf=0;this.ssh=_.t;this.sen=_.q;this.shl=this.itm=_.r};_.te.prototype.j=function(a){this.b.or(this.bc,a)};_.te.prototype.J=function(){this.b.oc(this.bc)};_.ue.prototype.sm=function(a,c){this.Ib.lk(new _.te(a,this));this.n=c};_.ue.prototype.sh=function(){this.Ib.show()};_.ue.prototype.hi=function(){this.Ib.fj()};_.ue.prototype.cl=function(){this.Ib.close()};_.ue.prototype.en=function(){this.Ib.enable()};_.ue.prototype.di=function(){this.Ib.disable()};_.ue.prototype.hl=function(a){this.Ib.Jm(a)};_.ue.prototype.vr=function(a,c){this.Ib.Hi(a,c)};


}catch(e){_._DumpException(e)}
try{


}catch(e){_._DumpException(e)}
try{
_.ve=function(a){this.bc=a;this.La=0;this.ze=_.t;this.wi=_.q;this.Ce=_.r};_.we=function(a){return 5==a.La||4==a.La};
_.xe=function(a,c,f){this.d=a||{};this.i=c||0;this.j=f||0;a={};c=(0,_.D)(this.rg,this);a.fc=c;c=(0,_.D)(this.vf,this);a.rc=c;c=(0,_.D)(this.Df,this);a.sc=c;c=(0,_.D)(this.ke,this);a.hc=c;c=(0,_.D)(this.Vd,this);a.cc=c;c=(0,_.D)(this.bj,this);a.os=c;c=(0,_.D)(this.aj,this);a.or=c;c=(0,_.D)(this.Zi,this);a.oh=c;c=(0,_.D)(this.Xi,this);a.oc=c;c=(0,_.D)(this.Yi,this);a.oe=c;c=(0,_.D)(this.$i,this);a.oi=c;this.b=a};
_.ye=function(a,c){var f=a.j-a.i;0<f&&(f=(0,window.setTimeout)((0,_.D)(function(){(0,_.we)(c)||(c.La=4,this.Vd(c.dc()))},a),f),c.Ce=f)};_.ze=function(a,c){c.Ce!=_.r&&((0,window.clearTimeout)(c.Ce),c.Ce=_.r)};_.Ae=function(a,c){(0,_.ze)(a,c);c.La=5;var f=a.d,g;for(g in f)f[g]==c&&delete f[g]};_.Be=function(a,c){return a.d[c.n]};_.Ce=function(a){this.b=a};_.De=function(){_.xe.call(this)};
_.Ee=function(a){if(window.___jsl.man)a(window.___jsl.man);else if(window.gbar){var c=function(){var c=new _.Ce(window.gbar.wg);window.___jsl.man=c;a(c)};window.gbar.wg?c():window.gbar.qm(c)}else c=new _.De,window.___jsl.man=c,a(c)};_.Fe=function(){return window.___jsl.man};_.ve.prototype.dc=(0,_.x)("bc");_.ve.prototype.isEnabled=(0,_.x)("wi");_.ve.prototype.ia=(0,_.ba)("wi");
_.C=_.xe.prototype;_.C.vf=function(a,c,f){try{a=a+(c!=_.r?"_"+c:""),f.sm(this.b,a),this.d[a]=new _.ve(f)}catch(g){return _.t}return _.q};_.C.rg=function(a,c){var f=this.d[a+(c!=_.r?"_"+c:"")];return f?f.dc():_.r};_.C.Df=function(a){var c=(0,_.Be)(this,a);if(c&&(2==c.La||3==c.La)&&c.isEnabled()&&!c.ze){try{a.sh()}catch(f){}c.ze=_.q}};_.C.ke=function(a){var c=(0,_.Be)(this,a);if(c&&(2==c.La||3==c.La||(0,_.we)(c))&&c.ze){try{a.hi()}catch(f){}c.ze=_.t}};
_.C.Vd=function(a){var c=(0,_.Be)(this,a);if(c&&5!=c.La){try{this.ke(a),a.cl()}catch(f){}(0,_.Ae)(this,c)}};_.C.bj=function(a){var c=(0,_.Be)(this,a);c&&0==c.La&&(this.i?(a=(0,window.setTimeout)((0,_.D)(function(){(0,_.we)(c)||(0,_.ye)(this,c)},this),this.i),c.Ce=a):(0,_.ye)(this,c),c.La=1)};_.C.aj=function(a){if((a=(0,_.Be)(this,a))&&!(0,_.we)(a)&&1==a.La)(0,_.ze)(this,a),a.La=3};_.C.Zi=function(a){if((a=(0,_.Be)(this,a))&&!(0,_.we)(a))a.ze=_.t};
_.C.Xi=function(a){var c=(0,_.Be)(this,a);if(c&&!(0,_.we)(c)){try{this.ke(a)}catch(f){}(0,_.Ae)(this,c)}};_.C.Yi=function(a){if((a=(0,_.Be)(this,a))&&!(0,_.we)(a))a.La=4,this.Vd(a.dc())};_.C.$i=function(a,c){var f=(0,_.Be)(this,a);f&&!(0,_.we)(f)&&(2<=c&&4>=c&&!(0,_.we)(f))&&((0,_.ze)(this,f),f.La=2)};
_.C=_.Ce.prototype;_.C.vf=function(a,c,f){return this.b.rc(a,c,f)};_.C.rg=function(a,c){return this.b.fc(a,c)};_.C.Df=function(a){this.b.sc(a)};_.C.ke=function(a){this.b.hc(a)};_.C.Vd=function(a){this.b.cc(a)};_.C.bj=function(a){this.b.os(a)};_.C.aj=function(a,c){this.b.or(a,c)};_.C.Zi=function(a){this.b.oh(a)};_.C.Xi=function(a){this.b.oc(a)};_.C.Yi=function(a,c,f,g,h,k){this.b.oe(a,c,f,g,h,k)};_.C.$i=function(a,c,f,g){this.b.oi(a,c,f,g)};
(0,_.E)(_.De,_.xe);

}catch(e){_._DumpException(e)}
try{
_.Ge=function(a){if("complete"===_.re.readyState)a();else{var c=_.t,f=function(){if(!c)return c=_.q,a.apply(this,arguments)};_.qe.addEventListener?(_.qe.addEventListener("load",f,_.t),_.qe.addEventListener("DOMContentLoaded",f,_.t)):_.qe.attachEvent&&(_.qe.attachEvent("onreadystatechange",function(){"complete"===_.re.readyState&&f.apply(this,arguments)}),_.qe.attachEvent("onload",f))}};_.He=function(){var a;if((a=window.Object.create)&&_.Ie.test(a))a=a(_.r);else{a={};for(var c in a)a[c]=_.n}return a};
_.Je=function(a){for(var c=0;c<this.length;c++)if(this[c]===a)return c;return-1};_.Ke=function(a){var c=(0,_.L)(a);return"undefined"!==typeof c?c:(0,_.L)("gwidget/"+a)};_.Le=function(a){return function(c){var f=a;"number"===typeof c?f=c:"string"===typeof c&&(f=c.indexOf("px"),-1!=f&&(c=c.substring(0,f)),f=(0,window.parseInt)(c,10));return f}};_.Me=function(a){"string"===typeof a&&(a=window[a]);return"function"===typeof a?a:_.r};_.Ne=function(a){return a.$o&&window.gbar&&window.gapi.load};
_.Oe=function(a,c){var f=new _.Pe;f.t.start=c.t.start;f.t.blt=c.t.blt;var g=c.t.rpcqi;g&&(f.t.rpcqi=g);f.name=a.Wb;f.tick("_widget");(0,_.me)(_.Qe,"csi",[]).push(f);return f};_.Re=function(a,c,f,g){return _.Q.open(a,c,f,g)};_.Se=function(a,c){for(var c=c||[],f=[],g=0;g<c.length;g++)f.push(a+c[g]);return f};_.Te=function(a,c){for(var f in _.Ue)if(_.Ue.hasOwnProperty(f)){var g=_.Ue[f][1];g&&!c.hasOwnProperty(g)&&(c[g]=a[g])}return c};
_.Ve=function(a,c){var f={},g;for(g in a)a.hasOwnProperty(g)&&(f[a[g][1]||g]=(a[g]&&a[g][0]||_.We)(c[g],c,_.Xe));return f};_.Ye=function(a,c,f,g){var h=(0,_.Ve)(a.fa,f);a.$j.push({element:c,fa:h,Fd:(0,_.Te)(h,(0,_.Ve)(a.Sj,f)),Id:g,mm:!!f["data-onload"]})};_.Ze=function(a){function c(){for(var c=a.$j,g=a.uh;0<c.length;)g(c.shift())}(0,_.Ne)(a)?(0,_.Ee)(c):c()};_.We=function(a){return a};_.$e=function(){};_.af=function(a){this.d=a;this.b=_.r};_.Ie=/\[native code\]/;_.bf={};
if(window.__gapi_jstiming__){window.__gapi_jstiming__.ki={};window.__gapi_jstiming__.Ao=1;_.cf=function(a,c,f){var g=a.t[c],h=a.t.start;if(g&&(h||f))return g=a.t[c][0],f!=_.n?h=f:h=h[0],g-h};window.__gapi_jstiming__.getTick=_.cf;window.__gapi_jstiming__.getLabels=function(a){var c=[],f;for(f in a.t)c.push(f);return c};_.df=function(a,c,f){var g="";window.__gapi_jstiming__.pt&&(g+="&srt="+window.__gapi_jstiming__.pt);try{window.external&&window.external.tran?g+="&tran="+window.external.tran:window.gtbExternal&&
window.gtbExternal.tran?g+="&tran="+window.gtbExternal.tran():window.chrome&&window.chrome.csi&&(g+="&tran="+window.chrome.csi().tran)}catch(h){}var k=window.chrome;if(k&&(k=k.loadTimes)){k().wasFetchedViaSpdy&&(g+="&p=s");if(k().wasNpnNegotiated){var g=g+"&npn=1",m=k().npnNegotiatedProtocol;m&&(g+="&npnv="+(window.encodeURIComponent||window.escape)(m))}k().wasAlternateProtocolAvailable&&(g+="&apa=1")}var p=a.t,s=p.start,k=[],m=[],u;for(u in p)if("start"!=u&&0!=u.indexOf("_")){var w=p[u][1];w?p[w]&&
m.push(u+"."+(0,_.cf)(a,u,p[w][0])):s&&k.push(u+"."+(0,_.cf)(a,u))}if(c)for(var A in c)g+="&"+A+"="+c[A];(c=f)||(c="https:"==window.document.location.protocol?"https://csi.gstatic.com/csi":"http://csi.gstatic.com/csi");a=[c,"?v=3","&s="+(window.__gapi_jstiming__.sn||"gwidget")+"&action=",a.name,m.length?"&it="+m.join(","):"","",g,"&rt=",k.join(",")].join("");if(!a)return"";var g=new window.Image,B=window.__gapi_jstiming__.Ao++;window.__gapi_jstiming__.ki[B]=g;g.onload=g.onerror=function(){window.__gapi_jstiming__&&
delete window.__gapi_jstiming__.ki[B]};g.src=a;g=_.r;return a};window.__gapi_jstiming__.report=function(a,c,f){if("prerender"==window.document.webkitVisibilityState){var g=_.t,h=function(){if(!g){c?c.prerender="1":c={prerender:"1"};var k;"prerender"==window.document.webkitVisibilityState?k=_.t:((0,_.df)(a,c,f),k=_.q);k&&(g=_.q,window.document.removeEventListener("webkitvisibilitychange",h,_.t))}};window.document.addEventListener("webkitvisibilitychange",h,_.t);return""}return(0,_.df)(a,c,f)}};
_.Qe=(0,_.me)(_.qe,"___jsl",(0,_.He)());(0,_.me)(_.Qe,"I",0);(0,_.me)(_.Qe,"hel",10);_.hf=["div"];_.jf="onload";_.kf=_.q;_.lf=window.__gapi_jstiming__;_.Pe=_.lf&&_.lf.Timer;_.mf=_.lf&&_.lf.load;_.nf=_.lf&&_.lf.report;_.of=_.Pe&&_.mf&&_.nf;_.Xe=_.r;_.Xe=(0,_.L)();(0,_.L)("gwidget");_.pf=(0,_.Ke)("parsetags");_.jf="explicit"===_.pf||"onload"===_.pf?_.pf:_.jf;_.qf=(0,_.Ke)("google_analytics");"undefined"!==typeof _.qf&&(_.kf=!!_.qf);_.rf={};_.rf.width=[(0,_.Le)(450)];_.rf.height=[(0,_.Le)(24)];_.rf.callback=[_.Me];_.rf.onready=[_.Me];
_.rf.lang=[function(){return(0,_.Ke)("lang")||"en-US"},"hl"];_.rf.iloader=[function(){return _.Qe.ILI},"iloader"];_.Ue=_.rf;
_.ef={nb:function(a){function c(a){for(var c={},f=0;f<a.length;++f)c[a[f].toLowerCase()]=1;c[h.Jk]=1;h.kh=c}function f(){"onload"===_.jf&&p.go()}var g,h={};h.Wb=a[0];h.Ph=-1;h.Ik="___"+h.Wb+"_";h.Jk="g:"+h.Wb;h.Jn="g-"+h.Wb;h.$j=[];h.fa={};h.Wf=[];h.kg=[];a[1]&&(h.Sj=a[1]);h.fa=a[2]||{};for(var k in _.Ue)_.Ue.hasOwnProperty(k)&&!h.fa.hasOwnProperty(k)&&(h.fa[k]=_.Ue[k]);a[3]&&(h.Wf=a[3]);a[4]&&c(a[4]);a[5]&&(h.Hd=a[5]);h.$o=a[7]===_.q;h.to=a[8];h.kh||c(_.hf);if(a=a[6])if("number"==typeof a.length){h.kg=
a;for(var m=a.length-1;0<=m;--m)h.fa[a[m]]=[_.Me]}else for(m in a)a.hasOwnProperty(m)&&!h.fa.hasOwnProperty(m)&&(h.kg.push(m),h.fa[m]=a[m]);h.uh=function(a){function c(){var a="",f="m"+(window.navigator.userAgent.match(/iPhone|iPad|Android|PalmWebOS|Maemo|Bada/)?"1":"0"),g="n"+Vo;try{var h=(0,_.Se)("e",(0,_.L)("lexps"));h.push(g);h.push(f);0==Vo&&h.push(f+g);h.push(_.jf);h.push("l"+((0,_.L)("isPlusUser")?"1":"0"));f=h;if(window.performance){var k=window.performance.timing;if(k){var m=k.navigationStart,
p=k.domContentLoadedEventStart;if(m&&p){k=(p-m)/1E3;1>k&&(k=1);var s=window.Math.floor(window.Math.log(k)/window.Math.log(2));6>=s&&f.push("p_gt"+window.Math.pow(2,s)+"s")}}}h=(0,_.Se)("abc_",h);a=h.join(",")}catch(u){}(0,_.nf)(Yb,{e:a});Wo++;Yb=(0,_.Oe)(Ej,_.mf)}function f(a,c){rb.Y("ready",a);_.P.N("widget-interactive-"+rb.id,a);_.P.N("widget-csi-tick-"+rb.id,c)}function g(a){var a=a||rb,c=rb.Te(a.width);c&&Qg.style.width!=c.Ec&&(Qg.style.width=c.Ec);if((a=rb.Te(a.height))&&Qg.style.height!=a.Ec)Qg.style.height=
a.Ec}h.Ph++;var k=[];h.Hd&&(k[0]=a.element,k[1]=a.Id,h.Hd("s",k),a.Id=k[1]);var m=a.element,p=m.parentNode,s=a.fa;if(0===a.Id){var T=window.document.createElement("div");p.insertBefore(T,m);p.removeChild(m);m=T}T=m.style;if(m.id){if(3===a.Id&&0===m.id.indexOf(h.Ik)){var R=m.nextSibling;R&&R.getAttribute("data-gapistub")&&p.removeChild(R);T.cssText=""}}else{var p=m,R=h.Ik,U=h.Wb,na=(0,_.me)(_.Qe,"WI",(0,_.He)());window.Object.prototype.hasOwnProperty.call(na,U)||(na[U]=0);var uc=na[U];na[U]=uc+1;p.id=
R+uc}s.height&&(T.height=s.height+"px");s.width&&(T.width=s.width+"px");T.display||(T.display="inline-block");(0,_.Ne)(h)&&(T.display="none");(0,_.ne)(m);var vc=":"+h.Wb;":plus"==vc&&(a.Fd&&a.Fd.action)&&(vc+="_"+a.Fd.action);var T={},p=h.Wf[0],R=s.callback,sb=h.Wf[1];if(sb&&_.kf)var Xv=R||(0,_.v)(),R=function(a){var c=sb(a);if(c&&window._gat)try{var f=window._gat._getTrackerByName("~0");f&&"UA-XXXXX-X"!=f._getAccount()?f._trackSocial("Google",c,a.href||_.r):window._gaq&&window._gaq.push(["_trackSocial",
"Google",c,a.href||_.r])}catch(g){}Xv(a)};p&&R&&(T[p]=R);p=h.kg;for(R=p.length-1;0<=R;--R){var db=p[R];(U=s[db])&&(T[db]=U)}p={};for(db in a.Fd)a.Fd[db]!=_.r&&(p[db]=a.Fd[db]);db={container:m.id,style:"inline",height:s.height,width:s.width};if(3===a.Id){if(!_.Q.aa("attach")){var zd={},ff=_.Q.aa("inline"),wc;for(wc in ff)ff.hasOwnProperty(wc)&&(zd[wc]=ff[wc]);zd.open=function(a){var c;a:{c=window.document.getElementById(a.ba().container).getElementsByTagName("IFRAME");for(var f=0;f<c.length;++f){var g=
c[f];if(g.id&&/^I\d+_\d+$/.test(g.id)){c=g;break a}}c=_.n}return c?ff.attach(a,c):ff.open(a)};_.Q.ja("attach",zd)}db.style="attach"}else if((0,_.Ne)(h)){db._ct=h.Wb;db._ci=h.Ph;if(!_.Q.aa("inline-managed")){wc={};var gf=_.Q.aa("inline");for(zd in gf)gf.hasOwnProperty(zd)&&(wc[zd]=gf[zd]);wc.open=function(a){gf.open(a);var c=new _.ue(new _.af(a));(0,_.Fe)().vf(a.ba()._ct,a.ba()._ci,c)&&(a=c[_.bf.Zk.el],a.b&&(a=a.b,a.b.os(a.bc)))};wc.onready=function(a){gf.onready(a);var c=(0,_.Fe)();if(a=c.rg(a.ba()._ct,
a.ba()._ci)){var f=a[_.bf.Zk.el];f.b&&f.b.j({});c.Df(a)}};_.Q.ja("inline-managed",wc)}db.style="inline-managed"}h.Hd&&(k[2]=db,k[3]=p,k[4]=T,h.Hd("i",k),a.Id=k[1]);var rb=function(a){var c=_.Re.apply(_.r,[vc].concat([].slice.call(arguments,0)));if(s.onready){var f=_.t,g=function(){f||(f=_.q,s.onready.call(_.r))};c.Y("ready",g);c.Y("renderstart",g)}(0,_.$e)(c);return c}(db,p,T),Qg=m;rb.Y("ready",g);rb.Y("renderstart",g);rb.Y("resize",g);var Ej=h,Xo=a.mm;if(_.of){var Vo=Ej.Ph,Yb=(0,_.Oe)(Ej,_.mf),Yo=
_.t,Zo=function(){if(!Yo){Yo=_.q;var a=rb.ca()["data-csi-wdt"]||_.n;Yb.tick("wdi","_widget",a);Xo&&Yb.tick("wdt",_.n,a)}};rb.Y("renderstart",Zo);var $o=_.t,Wo=0;f(function(){$o||($o=_.q,Zo(),Yb.tick("wri","_widget"),Xo&&Yb.tick("wrt"),(0,_.Ge)(c))},function(a,f,g,h){if(h!=_.r)f=(new window.Date).getTime(),Yb.tick("_"+a,_.n,f),Yb.tick(a,"_"+a,f+h);else{if(f&&!Yb.t[f])return;Yb.tick(a,f||_.n,g||_.n)}0<Wo&&c()})}else a=(0,_.v)(),f(a,a);k[5]=rb;h.Hd&&h.Hd("e",k)};g=h;if(m=g.to)for(a=0;a<m.length;a++)(new window.Image).src=
m[a];var p={O:function(a,c,f){a=("string"===typeof a?window.document.getElementById(a):a)||_.n;c=c||{};c.callback=f||c.callback;a&&1===a.nodeType&&(0,_.Ye)(g,a,c,1);(0,_.Ze)(g)},go:function(a){if(a=("string"===typeof a?window.document.getElementById(a):a)||window.document.body){var c;c=[];for(var f=a.getElementsByTagName("iframe"),h={},k=0;k<f.length;++k){var m=f[k].parentNode,p=m.id;if("div"==m.tagName.toLowerCase()&&p&&!h[p]){var s;a:{s=g;var T=m,R=T.getAttribute("data-gwattr");if(R!=_.r){for(var R=
R.split(":"),U={},na=0;na<R.length;++na){var uc=R[na].split("="),vc=window.decodeURIComponent(uc[0]),uc=window.decodeURIComponent(uc[1]);U[vc]=uc}if(U[">type"]===s.Wb){T.removeAttribute("data-gwattr");s=U;break a}}s=_.n}s&&(c.push({element:m,Uf:s}),h[p]=1)}}for(f=0;f<c.length;++f)h=c[f],(0,_.Ye)(g,h.element,h.Uf,3);c=[];a=a.getElementsByTagName("*");f=(0,window.RegExp)("(?:^|\\s)"+g.Jn+"(?:$|\\s)");for(h=0;h<a.length;++h)if(k=a[h],m=k.nodeName.toLowerCase(),!k.getAttribute("data-gapistub")&&(g.kh[m]||
g.kh["*"])){p="";if(m!==g.Jk&&(p="data-",!f.test(k.className||k.getAttribute("class"))))continue;s=m={};T=g.Sj;R=k;U=p;na=_.n;for(na in T)T.hasOwnProperty(na)&&(s[na]=R.getAttribute(U+na));s=m;T=g.fa;R=k;U=_.n;for(U in T)T.hasOwnProperty(U)&&(s[U]=R.getAttribute(p+U));c.push({element:k,Uf:m})}for(f=0;f<c.length;++f)h=c[f],(0,_.Ye)(g,h.element,h.Uf,0);(0,_.Ze)(g)}},b:function(){_.Qe.WI=(0,_.He)()}},m=g.Wb,a=(0,_.me)(_.Qe,"sws",[]);if(!(0<=_.Je.call(a,m))){if("complete"!==_.re.readyState)try{f()}catch(s){}(0,_.Ge)(f)}return p}};
_.bf=_.bf||{};_.C=_.af.prototype;_.C.lk=(0,_.ba)("b");_.C.Hi=function(a,c){c({})};_.C.show=function(){this.d.Q().style.display="inline-block"};_.C.fj=function(){this.d.Q().style.display="none"};_.C.close=function(){this.d.close({})};_.C.enable=(0,_.v)();_.C.disable=(0,_.v)();


}catch(e){_._DumpException(e)}
try{
_.lq=(window.gapi||{}).load;

}catch(e){_._DumpException(e)}
try{
_.Q.Af("bubble",function(a){(0,_.lq)("iframes-styles-bubble",a)});

}catch(e){_._DumpException(e)}
try{
_.zp=function(a,c,f){return"string"==typeof a&&c[a.toLowerCase()]?a.toLowerCase():f};_.Ap=function(a){var c=window.document.createElement("div"),f=window.document.createElement("a");f.href=a;c.appendChild(f);c.innerHTML=c.innerHTML;return c.firstChild.href};_.Bp=function(){return window.location.origin||window.location.protocol+"//"+window.location.host};
_.Cp=function(a,c,f,g){if(a)a=(0,_.Ap)(a);else a:{a=(a=g)||"canonical";c=window.document.getElementsByTagName("link");f=0;for(g=c.length;f<g;f++){var h=c[f],k=h.getAttribute("rel");if(k&&k.toLowerCase()==a&&(h=h.getAttribute("href")))if(h=(0,_.Ap)(h)){a=h;break a}}a=window.location.href}return a};_.Dp=function(a){a.source=[_.r,"source"];a.expandTo=[_.r,"expandTo"];a.align=[_.Ep];a.annotation=[_.Fp];a.origin=[_.Bp]};_.Gp=function(a,c){if("string"==typeof a){var f;for(f=0;f<c.length;f++)if(c[f]==a.toLowerCase())return a.toLowerCase()}};
_.Ep=function(a){return(0,_.Gp)(a,_.Hp)};_.Fp=function(a){return(0,_.Gp)(a,_.Ip)};_.Jp=function(a){return"string"==typeof a?""!=a&&"0"!=a&&"false"!=a.toLowerCase():!!a};_.Kp=function(a){var c=(0,window.parseInt)(a,10);if(c==a)return(0,window.String)(c)};_.Lp=function(a){if((0,_.Jp)(a))return"true"};_.Mp=function(a){return(0,_.zp)(a,_.Np,"standard")};_.Op=function(a,c){return"tall"==(0,_.Mp)(c)?"true":a==_.r||(0,_.Jp)(a)?"true":"false"};
_.Hp=["left","right"];_.Ip="inline bubble none only pp vertical-bubble".split(" ");_.Np={tall:{"true":{width:50,height:60},"false":{width:50,height:24}},small:{"false":{width:24,height:15},"true":{width:70,height:15}},medium:{"false":{width:32,height:20},"true":{width:90,height:20}},standard:{"false":{width:38,height:24},"true":{width:106,height:24}}};
_.Pp={href:[_.Cp,"url"],width:[_.Kp],size:[_.Mp],resize:[_.Lp],autosize:[_.Lp],count:[function(a,c){return(0,_.Op)(c.count,c.size)}],db:[function(a,c,f){a==_.r&&f&&(a=f.db,a==_.r&&(a=f.gwidget&&f.gwidget.db));return(0,_.Jp)(a)?1:_.n}],ecp:[function(a,c,f){a==_.r&&f&&(a=f.ecp,a==_.r&&(a=f.gwidget&&f.gwidget.ecp));if((0,_.Jp)(a))return"true"}],textcolor:[function(a){if("string"==typeof a&&a.match(/^[0-9A-F]{6}$/i))return a}],drm:[_.Lp],recommendations:[],fu:[],ad:[_.Lp],cr:[_.Kp],ag:[_.Kp],"fr-ai":[], "fr-sigh":[]};


}catch(e){_._DumpException(e)}
try{
_.Jw=function(a,c,f){a=(0,_.Fp)(a);c=(0,_.Mp)(c);if(""!=a){if("inline"==a||"only"==a)return a=450,f.width&&(a=120<f.width?f.width:120),{width:a,height:_.Np[c]["false"].height};if("bubble"!=a){if("none"==a)return _.Np[c]["false"];if("pp"==a)return _.Kw}}return _.Np[c]["true"]};_.Kw={width:180,height:35};
_.Lw={"0":"plusone"};_.Mw=(0,_.L)("iframes/plusone/preloadUrl");_.Mw&&(_.Lw[8]=_.Mw);(0,_.Dp)(_.Pp);_.Lw[1]=_.Pp;_.Lw[2]={width:[function(a,c){return c.annotation?(0,_.Jw)(c.annotation,c.size,c).width:_.Np[(0,_.Mp)(c.size)][(0,_.Op)(c.count,c.size)].width}],height:[function(a,c){return c.annotation?(0,_.Jw)(c.annotation,c.size,c).height:_.Np[(0,_.Mp)(c.size)][(0,_.Op)(c.count,c.size)].height}]};_.Lw[3]=["onPlusOne",function(a){return"on"==a.state?"+1":_.r}];_.Lw[4]=["div","button"]; _.Lw[6]=["onstartinteraction","onendinteraction","onpopup"];_.Ja=_.Ka=_.ef.nb(_.Lw);
(0,_.M)("gapi.plusone.render",_.Ka.O);(0,_.M)("gapi.plusone.go",_.Ka.go);(0,_.M)("googleapisv0.plusone.render",_.Ja.O);(0,_.M)("googleapisv0.plusone.go",_.Ja.go);

}catch(e){_._DumpException(e)}
});

// Copyright 2002-2012 Google Inc.
